## **Upload Dataset**

In [1]:
from google.colab import files
uploaded=files.upload()

Saving bank.csv to bank.csv

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import BatchNormalization

## **Reading the data**

In [62]:
data=pd.read_csv('bank.csv',sep=';')

### **Data Head**

In [63]:
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

## **Data Information**

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

## **Data Summary**

In [65]:
data.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

## **Data Preprocessing**

### **Identifying and handling misisng values in dataset**

In [66]:
pd.isnull(data).sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

### **Identifying duplicates and removing it**

In [67]:
data.duplicated().sum()

0

# **Addressing Outliers**

# **Identify categorical columns**

In [68]:
print(f"Various Job Categories in dataset :{data['job'].unique()}")

print(f"Various Marital Status in dataset:{data['marital'].unique()}")

print(f"Various education Status in dataset:{data['education'].unique()}")

print(f"Various defalut Status in dataset:{data['default'].unique()}")

print(f"Various housing Status in dataset:{data['housing'].unique()}")

print(f"Various loan status in dataset:{data['loan'].unique()}")

print(f"Various contact status in dataset:{data['contact'].unique()}")

print(f"Various month status in dataset:{data['month'].unique()}")

print(f"Various poutcome status in dataset:{data['poutcome'].unique()}")

print(f"Various Y(Target variable ) status in dataset:{data['y'].unique()}")

Various Job Categories in dataset :['unemployed' 'services' 'management' 'blue-collar' 'self-employed'
 'technician' 'entrepreneur' 'admin.' 'student' 'housemaid' 'retired'
 'unknown']
Various Marital Status in dataset:['married' 'single' 'divorced']
Various education Status in dataset:['primary' 'secondary' 'tertiary' 'unknown']
Various defalut Status in dataset:['no' 'yes']
Various housing Status in dataset:['no' 'yes']
Various loan status in dataset:['no' 'yes']
Various contact status in dataset:['cellular' 'unknown' 'telephone']
Various month status in dataset:['oct' 'may' 'apr' 'jun' 'feb' 'aug' 'jan' 'jul' 'nov' 'sep' 'mar' 'dec']
Various poutcome status in dataset:['unknown' 'failure' 'other' 'success']
Various Y(Target variable ) status in dataset:['no' 'yes']

# **One Hot colding to convert categorical columns into numerical values for further implementations**

In [69]:
# Identify categorical columns
binary_cols = ['default', 'housing', 'loan', 'y']  # Example binary columns (yes/no)
multi_category_cols = ['job', 'marital', 'education', 'contact', 'month', 'poutcome']  # Multi-category

# Convert binary columns to 0 & 1
for col in binary_cols:
    data[col] = data[col].map({'yes':1, 'no':0})

# Apply one-hot encoding for multi-category columns
data = pd.get_dummies(data, columns=multi_category_cols, drop_first=True)

# Display transformed dataset
print(data.head())

   age  default  balance  housing  loan  day  duration  campaign  pdays  \
0   30        0     1787        0     0   19        79         1     -1
1   33        0     4789        1     1   11       220         1    339
2   35        0     1350        1     0   16       185         1    330
3   30        0     1476        1     1    3       199         4     -1
4   59        0        0        1     0    5       226         1     -1

   previous  ...  month_jul  month_jun  month_mar  month_may  month_nov  \
0         0  ...      False      False      False      False      False
1         4  ...      False      False      False       True      False
2         1  ...      False      False      False      False      False
3         0  ...      False       True      False      False      False
4         0  ...      False      False      False       True      False

   month_oct  month_sep  poutcome_other  poutcome_success  poutcome_unknown
0       True      False           False             False              True
1      False      False           False             False             False
2      False      False           False             False             False
3      False      False           False             False              True
4      False      False           False             False              True

[5 rows x 43 columns]

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  4521 non-null   int64
 1   default              4521 non-null   int64
 2   balance              4521 non-null   int64
 3   housing              4521 non-null   int64
 4   loan                 4521 non-null   int64
 5   day                  4521 non-null   int64
 6   duration             4521 non-null   int64
 7   campaign             4521 non-null   int64
 8   pdays                4521 non-null   int64
 9   previous             4521 non-null   int64
 10  y                    4521 non-null   int64
 11  job_blue-collar      4521 non-null   bool
 12  job_entrepreneur     4521 non-null   bool
 13  job_housemaid        4521 non-null   bool
 14  job_management       4521 non-null   bool
 15  job_retired          4521 non-null   bool
 16  job_self-employed    4521 non-null   bool
 17  job_services         4521 non-null   bool
 18  job_student          4521 non-null   bool
 19  job_technician       4521 non-null   bool
 20  job_unemployed       4521 non-null   bool
 21  job_unknown          4521 non-null   bool
 22  marital_married      4521 non-null   bool
 23  marital_single       4521 non-null   bool
 24  education_secondary  4521 non-null   bool
 25  education_tertiary   4521 non-null   bool
 26  education_unknown    4521 non-null   bool
 27  contact_telephone    4521 non-null   bool
 28  contact_unknown      4521 non-null   bool
 29  month_aug            4521 non-null   bool
 30  month_dec            4521 non-null   bool
 31  month_feb            4521 non-null   bool
 32  month_jan            4521 non-null   bool
 33  month_jul            4521 non-null   bool
 34  month_jun            4521 non-null   bool
 35  month_mar            4521 non-null   bool
 36  month_may            4521 non-null   bool
 37  month_nov            4521 non-null   bool
 38  month_oct            4521 non-null   bool
 39  month_sep            4521 non-null   bool
 40  poutcome_other       4521 non-null   bool
 41  poutcome_success     4521 non-null   bool
 42  poutcome_unknown     4521 non-null   bool
dtypes: bool(32), int64(11)
memory usage: 529.9 KB

# **Feature Selection**

In [71]:
X=data.drop('y',axis=1)
y=data['y']

# **Spliting the dataset**

In [72]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

## **Scaling the Features**
### We will use StandardScaling for scaling the feature since we are using neural network (usually prefered)

In [73]:
Scaler=StandardScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.fit_transform(X_test)

### **Building the Recurrent neural network Model**

In [74]:
X_train_rnn = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_rnn = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))


# Define RNN model
model = Sequential()

# Input layer and first RNN layer
model.add(SimpleRNN(32, input_shape=(1, X_train_scaled.shape[1]),kernel_regularizer=l2(0.01),activation='relu', return_sequences=True))
model.add(Dropout(0.3))

# Second RNN layer
model.add(SimpleRNN(12, activation='relu'))
model.add(Dropout(0.3))

# Output layer (1 neuron for binary classification)
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Summary of the model
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_14 (SimpleRNN)            │ (None, 1, 32)               │           2,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 1, 32)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_15 (SimpleRNN)            │ (None, 12)                  │             540 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 12)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              13 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,953 (11.54 KB)

 Trainable params: 2,953 (11.54 KB)

 Non-trainable params: 0 (0.00 B)

## **Train the model**

In [75]:
# Train the model
history = model.fit(X_train_rnn, y_train, epochs=50, batch_size=32, validation_data=(X_test_rnn, y_test))

Epoch 1/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6427 - loss: 0.9708 - val_accuracy: 0.8909 - val_loss: 0.6217
Epoch 2/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8585 - loss: 0.6707 - val_accuracy: 0.8946 - val_loss: 0.5098
Epoch 3/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8854 - loss: 0.5144 - val_accuracy: 0.8946 - val_loss: 0.4365
Epoch 4/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8900 - loss: 0.4487 - val_accuracy: 0.8931 - val_loss: 0.3839
Epoch 5/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8863 - loss: 0.4085 - val_accuracy: 0.8976 - val_loss: 0.3478
Epoch 6/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9029 - loss: 0.3406 - val_accuracy: 0.8968 - val_loss: 0.3235
Epoch 7/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9024 - loss: 0.3277 - val_accuracy: 0.8954 - val_loss: 0.3061
Epoch 8/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9017 - loss: 0.3140 - val_accuracy: 0.8931 - val_loss: 0.2941
Epoch 9/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9024 - loss: 0.2918 - val_accuracy: 0.8917 - val_loss: 0.2838
Epoch 10/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9125 - loss: 0.2834 - val_accuracy: 0.8931 - val_loss: 0.2759
Epoch 11/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9017 - loss: 0.2770 - val_accuracy: 0.8961 - val_loss: 0.2706
Epoch 12/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8990 - loss: 0.2862 - val_accuracy: 0.8968 - val_loss: 0.2693
Epoch 13/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9084 - loss: 0.2484 - val_accuracy: 0.8961 - val_loss: 0.2656
Epoch 14/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9070 - loss: 0.2595 - val_accuracy: 0.8961 - val_loss: 0.2612
Epoch 15/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9021 - loss: 0.2619 - val_accuracy: 0.8931 - val_loss: 0.2591
Epoch 16/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9094 - loss: 0.2423 - val_accuracy: 0.8946 - val_loss: 0.2586
Epoch 17/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8972 - loss: 0.2574 - val_accuracy: 0.8976 - val_loss: 0.2577
Epoch 18/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9061 - loss: 0.2501 - val_accuracy: 0.8954 - val_loss: 0.2583
Epoch 19/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9085 - loss: 0.2405 - val_accuracy: 0.8939 - val_loss: 0.2583
Epoch 20/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9086 - loss: 0.2551 - val_accuracy: 0.8968 - val_loss: 0.2579
Epoch 21/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9235 - loss: 0.2302 - val_accuracy: 0.8961 - val_loss: 0.2563
Epoch 22/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9014 - loss: 0.2516 - val_accuracy: 0.8917 - val_loss: 0.2568
Epoch 23/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9120 - loss: 0.2345 - val_accuracy: 0.8968 - val_loss: 0.2540
Epoch 24/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9207 - loss: 0.2253 - val_accuracy: 0.8954 - val_loss: 0.2552
Epoch 25/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9214 - loss: 0.2355 - val_accuracy: 0.8909 - val_loss: 0.2563
Epoch 26/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9087 - loss: 0.2394 - val_accuracy: 0.8939 - val_loss: 0.2549
Epoch 27/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9215 - loss: 0.2196 - val_accuracy: 0.8968 - val_loss: 0.2554
Epoch 28/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9188 - loss: 0.2247 - val_accuracy: 0.8968 - val_loss: 0.2570
Epoch 29/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9154 - loss: 0.2248 - val_accuracy: 0.8976 - val_loss: 0.2577
Epoch 30/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9081 - loss: 0.2413 - val_accuracy: 0.8990 - val_loss: 0.2621
Epoch 31/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9078 - loss: 0.2410 - val_accuracy: 0.8946 - val_loss: 0.2631
Epoch 32/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9141 - loss: 0.2213 - val_accuracy: 0.8998 - val_loss: 0.2594
Epoch 33/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9162 - loss: 0.2279 - val_accuracy: 0.8976 - val_loss: 0.2608
Epoch 34/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9266 - loss: 0.2026 - val_accuracy: 0.9020 - val_loss: 0.2550
Epoch 35/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9176 - loss: 0.2129 - val_accuracy: 0.8946 - val_loss: 0.2617
Epoch 36/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9181 - loss: 0.2125 - val_accuracy: 0.8976 - val_loss: 0.2552
Epoch 37/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9284 - loss: 0.2073 - val_accuracy: 0.8998 - val_loss: 0.2606
Epoch 38/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9130 - loss: 0.2215 - val_accuracy: 0.8976 - val_loss: 0.2647
Epoch 39/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9224 - loss: 0.2089 - val_accuracy: 0.8961 - val_loss: 0.2624
Epoch 40/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9208 - loss: 0.2172 - val_accuracy: 0.8961 - val_loss: 0.2677
Epoch 41/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9208 - loss: 0.2198 - val_accuracy: 0.8976 - val_loss: 0.2636
Epoch 42/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9307 - loss: 0.2017 - val_accuracy: 0.8961 - val_loss: 0.2656
Epoch 43/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9152 - loss: 0.2215 - val_accuracy: 0.8976 - val_loss: 0.2699
Epoch 44/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9154 - loss: 0.2123 - val_accuracy: 0.8990 - val_loss: 0.2709
Epoch 45/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9327 - loss: 0.2002 - val_accuracy: 0.8961 - val_loss: 0.2659
Epoch 46/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9281 - loss: 0.2033 - val_accuracy: 0.8968 - val_loss: 0.2655
Epoch 47/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9132 - loss: 0.2216 - val_accuracy: 0.9013 - val_loss: 0.2684
Epoch 48/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9221 - loss: 0.2043 - val_accuracy: 0.9013 - val_loss: 0.2688
Epoch 49/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9269 - loss: 0.1983 - val_accuracy: 0.8968 - val_loss: 0.2737
Epoch 50/50
99/99 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9253 - loss: 0.2096 - val_accuracy: 0.8983 - val_loss: 0.2752

## **Prediction**

In [77]:
# Make predictions
y_pred_prob = model.predict(X_test_rnn)

# Convert probabilities to binary labels (0 or 1)
y_pred = (y_pred_prob > 0.5).astype(int)

43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

## **Prediction output**

In [78]:
for i, prediction in enumerate(y_pred):
  print(f"customer {i+1} will {'subscribe' if prediction == 1 else 'not subscribe'} to subscription  ")

customer 1 will not subscribe to subscription
customer 2 will subscribe to subscription
customer 3 will not subscribe to subscription
customer 4 will not subscribe to subscription
customer 5 will not subscribe to subscription
customer 6 will not subscribe to subscription
customer 7 will not subscribe to subscription
customer 8 will not subscribe to subscription
customer 9 will not subscribe to subscription
customer 10 will not subscribe to subscription
customer 11 will not subscribe to subscription
customer 12 will not subscribe to subscription
customer 13 will not subscribe to subscription
customer 14 will subscribe to subscription
customer 15 will not subscribe to subscription
customer 16 will not subscribe to subscription
customer 17 will not subscribe to subscription
customer 18 will not subscribe to subscription
customer 19 will not subscribe to subscription
customer 20 will not subscribe to subscription
customer 21 will not subscribe to subscription
customer 22 will not subscribe to subscription
customer 23 will subscribe to subscription
customer 24 will not subscribe to subscription
customer 25 will not subscribe to subscription
customer 26 will not subscribe to subscription
customer 27 will not subscribe to subscription
customer 28 will subscribe to subscription
customer 29 will not subscribe to subscription
customer 30 will not subscribe to subscription
customer 31 will not subscribe to subscription
customer 32 will not subscribe to subscription
customer 33 will not subscribe to subscription
customer 34 will not subscribe to subscription
customer 35 will not subscribe to subscription
customer 36 will not subscribe to subscription
customer 37 will subscribe to subscription
customer 38 will not subscribe to subscription
customer 39 will not subscribe to subscription
customer 40 will not subscribe to subscription
customer 41 will not subscribe to subscription
customer 42 will not subscribe to subscription
customer 43 will subscribe to subscription
customer 44 will not subscribe to subscription
customer 45 will not subscribe to subscription
customer 46 will not subscribe to subscription
customer 47 will not subscribe to subscription
customer 48 will not subscribe to subscription
customer 49 will not subscribe to subscription
customer 50 will not subscribe to subscription
customer 51 will not subscribe to subscription
customer 52 will not subscribe to subscription
customer 53 will not subscribe to subscription
customer 54 will not subscribe to subscription
customer 55 will not subscribe to subscription
customer 56 will not subscribe to subscription
customer 57 will subscribe to subscription
customer 58 will not subscribe to subscription
customer 59 will not subscribe to subscription
customer 60 will not subscribe to subscription
customer 61 will not subscribe to subscription
customer 62 will not subscribe to subscription
customer 63 will not subscribe to subscription
customer 64 will not subscribe to subscription
customer 65 will not subscribe to subscription
customer 66 will not subscribe to subscription
customer 67 will not subscribe to subscription
customer 68 will not subscribe to subscription
customer 69 will not subscribe to subscription
customer 70 will not subscribe to subscription
customer 71 will not subscribe to subscription
customer 72 will not subscribe to subscription
customer 73 will not subscribe to subscription
customer 74 will not subscribe to subscription
customer 75 will not subscribe to subscription
customer 76 will not subscribe to subscription
customer 77 will not subscribe to subscription
customer 78 will not subscribe to subscription
customer 79 will not subscribe to subscription
customer 80 will not subscribe to subscription
customer 81 will not subscribe to subscription
customer 82 will not subscribe to subscription
customer 83 will not subscribe to subscription
customer 84 will not subscribe to subscription
customer 85 will not subscribe to subscription
customer 86 will not subscribe to subscription
customer 87 will not subscribe to subscription
customer 88 will not subscribe to subscription
customer 89 will not subscribe to subscription
customer 90 will not subscribe to subscription
customer 91 will not subscribe to subscription
customer 92 will not subscribe to subscription
customer 93 will not subscribe to subscription
customer 94 will not subscribe to subscription
customer 95 will not subscribe to subscription
customer 96 will not subscribe to subscription
customer 97 will not subscribe to subscription
customer 98 will not subscribe to subscription
customer 99 will not subscribe to subscription
customer 100 will not subscribe to subscription
customer 101 will not subscribe to subscription
customer 102 will not subscribe to subscription
customer 103 will not subscribe to subscription
customer 104 will not subscribe to subscription
customer 105 will not subscribe to subscription
customer 106 will not subscribe to subscription
customer 107 will not subscribe to subscription
customer 108 will not subscribe to subscription
customer 109 will not subscribe to subscription
customer 110 will not subscribe to subscription
customer 111 will not subscribe to subscription
customer 112 will subscribe to subscription
customer 113 will not subscribe to subscription
customer 114 will not subscribe to subscription
customer 115 will not subscribe to subscription
customer 116 will not subscribe to subscription
customer 117 will not subscribe to subscription
customer 118 will subscribe to subscription
customer 119 will not subscribe to subscription
customer 120 will not subscribe to subscription
customer 121 will not subscribe to subscription
customer 122 will not subscribe to subscription
customer 123 will not subscribe to subscription
customer 124 will not subscribe to subscription
customer 125 will not subscribe to subscription
customer 126 will not subscribe to subscription
customer 127 will not subscribe to subscription
customer 128 will not subscribe to subscription
customer 129 will not subscribe to subscription
customer 130 will not subscribe to subscription
customer 131 will not subscribe to subscription
customer 132 will not subscribe to subscription
customer 133 will not subscribe to subscription
customer 134 will not subscribe to subscription
customer 135 will not subscribe to subscription
customer 136 will not subscribe to subscription
customer 137 will not subscribe to subscription
customer 138 will not subscribe to subscription
customer 139 will not subscribe to subscription
customer 140 will not subscribe to subscription
customer 141 will not subscribe to subscription
customer 142 will not subscribe to subscription
customer 143 will not subscribe to subscription
customer 144 will not subscribe to subscription
customer 145 will not subscribe to subscription
customer 146 will not subscribe to subscription
customer 147 will not subscribe to subscription
customer 148 will not subscribe to subscription
customer 149 will not subscribe to subscription
customer 150 will not subscribe to subscription
customer 151 will not subscribe to subscription
customer 152 will not subscribe to subscription
customer 153 will not subscribe to subscription
customer 154 will not subscribe to subscription
customer 155 will not subscribe to subscription
customer 156 will not subscribe to subscription
customer 157 will not subscribe to subscription
customer 158 will not subscribe to subscription
customer 159 will not subscribe to subscription
customer 160 will not subscribe to subscription
customer 161 will not subscribe to subscription
customer 162 will not subscribe to subscription
customer 163 will not subscribe to subscription
customer 164 will not subscribe to subscription
customer 165 will not subscribe to subscription
customer 166 will subscribe to subscription
customer 167 will not subscribe to subscription
customer 168 will not subscribe to subscription
customer 169 will not subscribe to subscription
customer 170 will subscribe to subscription
customer 171 will not subscribe to subscription
customer 172 will not subscribe to subscription
customer 173 will not subscribe to subscription
customer 174 will not subscribe to subscription
customer 175 will not subscribe to subscription
customer 176 will not subscribe to subscription
customer 177 will not subscribe to subscription
customer 178 will not subscribe to subscription
customer 179 will not subscribe to subscription
customer 180 will not subscribe to subscription
customer 181 will not subscribe to subscription
customer 182 will not subscribe to subscription
customer 183 will not subscribe to subscription
customer 184 will not subscribe to subscription
customer 185 will not subscribe to subscription
customer 186 will not subscribe to subscription
customer 187 will not subscribe to subscription
customer 188 will not subscribe to subscription
customer 189 will not subscribe to subscription
customer 190 will not subscribe to subscription
customer 191 will not subscribe to subscription
customer 192 will not subscribe to subscription
customer 193 will subscribe to subscription
customer 194 will not subscribe to subscription
customer 195 will not subscribe to subscription
customer 196 will not subscribe to subscription
customer 197 will not subscribe to subscription
customer 198 will not subscribe to subscription
customer 199 will not subscribe to subscription
customer 200 will not subscribe to subscription
customer 201 will not subscribe to subscription
customer 202 will not subscribe to subscription
customer 203 will subscribe to subscription
customer 204 will not subscribe to subscription
customer 205 will not subscribe to subscription
customer 206 will not subscribe to subscription
customer 207 will not subscribe to subscription
customer 208 will not subscribe to subscription
customer 209 will not subscribe to subscription
customer 210 will not subscribe to subscription
customer 211 will not subscribe to subscription
customer 212 will not subscribe to subscription
customer 213 will not subscribe to subscription
customer 214 will not subscribe to subscription
customer 215 will not subscribe to subscription
customer 216 will not subscribe to subscription
customer 217 will not subscribe to subscription
customer 218 will not subscribe to subscription
customer 219 will not subscribe to subscription
customer 220 will not subscribe to subscription
customer 221 will not subscribe to subscription
customer 222 will not subscribe to subscription
customer 223 will not subscribe to subscription
customer 224 will not subscribe to subscription
customer 225 will not subscribe to subscription
customer 226 will not subscribe to subscription
customer 227 will not subscribe to subscription
customer 228 will not subscribe to subscription
customer 229 will not subscribe to subscription
customer 230 will not subscribe to subscription
customer 231 will not subscribe to subscription
customer 232 will not subscribe to subscription
customer 233 will not subscribe to subscription
customer 234 will not subscribe to subscription
customer 235 will not subscribe to subscription
customer 236 will not subscribe to subscription
customer 237 will not subscribe to subscription
customer 238 will not subscribe to subscription
customer 239 will not subscribe to subscription
customer 240 will not subscribe to subscription
customer 241 will not subscribe to subscription
customer 242 will not subscribe to subscription
customer 243 will not subscribe to subscription
customer 244 will not subscribe to subscription
customer 245 will not subscribe to subscription
customer 246 will subscribe to subscription
customer 247 will not subscribe to subscription
customer 248 will not subscribe to subscription
customer 249 will not subscribe to subscription
customer 250 will not subscribe to subscription
customer 251 will not subscribe to subscription
customer 252 will not subscribe to subscription
customer 253 will not subscribe to subscription
customer 254 will not subscribe to subscription
customer 255 will not subscribe to subscription
customer 256 will not subscribe to subscription
customer 257 will subscribe to subscription
customer 258 will not subscribe to subscription
customer 259 will not subscribe to subscription
customer 260 will not subscribe to subscription
customer 261 will subscribe to subscription
customer 262 will not subscribe to subscription
customer 263 will not subscribe to subscription
customer 264 will not subscribe to subscription
customer 265 will not subscribe to subscription
customer 266 will not subscribe to subscription
customer 267 will not subscribe to subscription
customer 268 will not subscribe to subscription
customer 269 will not subscribe to subscription
customer 270 will not subscribe to subscription
customer 271 will not subscribe to subscription
customer 272 will not subscribe to subscription
customer 273 will not subscribe to subscription
customer 274 will not subscribe to subscription
customer 275 will not subscribe to subscription
customer 276 will not subscribe to subscription
customer 277 will not subscribe to subscription
customer 278 will not subscribe to subscription
customer 279 will not subscribe to subscription
customer 280 will not subscribe to subscription
customer 281 will not subscribe to subscription
customer 282 will not subscribe to subscription
customer 283 will not subscribe to subscription
customer 284 will not subscribe to subscription
customer 285 will not subscribe to subscription
customer 286 will not subscribe to subscription
customer 287 will not subscribe to subscription
customer 288 will not subscribe to subscription
customer 289 will not subscribe to subscription
customer 290 will not subscribe to subscription
customer 291 will not subscribe to subscription
customer 292 will not subscribe to subscription
customer 293 will not subscribe to subscription
customer 294 will not subscribe to subscription
customer 295 will not subscribe to subscription
customer 296 will not subscribe to subscription
customer 297 will not subscribe to subscription
customer 298 will not subscribe to subscription
customer 299 will not subscribe to subscription
customer 300 will not subscribe to subscription
customer 301 will not subscribe to subscription
customer 302 will not subscribe to subscription
customer 303 will not subscribe to subscription
customer 304 will not subscribe to subscription
customer 305 will not subscribe to subscription
customer 306 will not subscribe to subscription
customer 307 will not subscribe to subscription
customer 308 will not subscribe to subscription
customer 309 will not subscribe to subscription
customer 310 will not subscribe to subscription
customer 311 will not subscribe to subscription
customer 312 will not subscribe to subscription
customer 313 will not subscribe to subscription
customer 314 will not subscribe to subscription
customer 315 will not subscribe to subscription
customer 316 will not subscribe to subscription
customer 317 will not subscribe to subscription
customer 318 will not subscribe to subscription
customer 319 will not subscribe to subscription
customer 320 will subscribe to subscription
customer 321 will not subscribe to subscription
customer 322 will not subscribe to subscription
customer 323 will not subscribe to subscription
customer 324 will not subscribe to subscription
customer 325 will not subscribe to subscription
customer 326 will subscribe to subscription
customer 327 will not subscribe to subscription
customer 328 will not subscribe to subscription
customer 329 will not subscribe to subscription
customer 330 will not subscribe to subscription
customer 331 will not subscribe to subscription
customer 332 will not subscribe to subscription
customer 333 will not subscribe to subscription
customer 334 will not subscribe to subscription
customer 335 will not subscribe to subscription
customer 336 will not subscribe to subscription
customer 337 will not subscribe to subscription
customer 338 will not subscribe to subscription
customer 339 will not subscribe to subscription
customer 340 will not subscribe to subscription
customer 341 will not subscribe to subscription
customer 342 will not subscribe to subscription
customer 343 will subscribe to subscription
customer 344 will not subscribe to subscription
customer 345 will not subscribe to subscription
customer 346 will not subscribe to subscription
customer 347 will not subscribe to subscription
customer 348 will not subscribe to subscription
customer 349 will not subscribe to subscription
customer 350 will not subscribe to subscription
customer 351 will not subscribe to subscription
customer 352 will not subscribe to subscription
customer 353 will subscribe to subscription
customer 354 will not subscribe to subscription
customer 355 will not subscribe to subscription
customer 356 will subscribe to subscription
customer 357 will not subscribe to subscription
customer 358 will not subscribe to subscription
customer 359 will not subscribe to subscription
customer 360 will not subscribe to subscription
customer 361 will not subscribe to subscription
customer 362 will not subscribe to subscription
customer 363 will not subscribe to subscription
customer 364 will not subscribe to subscription
customer 365 will not subscribe to subscription
customer 366 will not subscribe to subscription
customer 367 will not subscribe to subscription
customer 368 will not subscribe to subscription
customer 369 will not subscribe to subscription
customer 370 will subscribe to subscription
customer 371 will not subscribe to subscription
customer 372 will not subscribe to subscription
customer 373 will not subscribe to subscription
customer 374 will subscribe to subscription
customer 375 will not subscribe to subscription
customer 376 will subscribe to subscription
customer 377 will not subscribe to subscription
customer 378 will not subscribe to subscription
customer 379 will not subscribe to subscription
customer 380 will not subscribe to subscription
customer 381 will not subscribe to subscription
customer 382 will not subscribe to subscription
customer 383 will not subscribe to subscription
customer 384 will not subscribe to subscription
customer 385 will not subscribe to subscription
customer 386 will not subscribe to subscription
customer 387 will not subscribe to subscription
customer 388 will not subscribe to subscription
customer 389 will not subscribe to subscription
customer 390 will not subscribe to subscription
customer 391 will not subscribe to subscription
customer 392 will not subscribe to subscription
customer 393 will not subscribe to subscription
customer 394 will not subscribe to subscription
customer 395 will not subscribe to subscription
customer 396 will not subscribe to subscription
customer 397 will not subscribe to subscription
customer 398 will not subscribe to subscription
customer 399 will not subscribe to subscription
customer 400 will not subscribe to subscription
customer 401 will not subscribe to subscription
customer 402 will not subscribe to subscription
customer 403 will not subscribe to subscription
customer 404 will not subscribe to subscription
customer 405 will not subscribe to subscription
customer 406 will not subscribe to subscription
customer 407 will not subscribe to subscription
customer 408 will not subscribe to subscription
customer 409 will not subscribe to subscription
customer 410 will not subscribe to subscription
customer 411 will not subscribe to subscription
customer 412 will not subscribe to subscription
customer 413 will not subscribe to subscription
customer 414 will not subscribe to subscription
customer 415 will not subscribe to subscription
customer 416 will not subscribe to subscription
customer 417 will not subscribe to subscription
customer 418 will not subscribe to subscription
customer 419 will not subscribe to subscription
customer 420 will not subscribe to subscription

## **Count No. of Employee able or unable to subscribe**

In [79]:
count_able = 0
count_unable=0

for prediction in y_pred:
  if prediction ==1 :
    count_able +=1
  else:
    count_unable +=1

print(f'No. of customer able to subscribe {count_able}')

print(f'No. of customer not able to subscribe {count_unable}')

No. of customer able to subscribe 102
No. of customer not able to subscribe 1255

# **Evaluate Model**

In [80]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test_rnn, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8963 - loss: 0.2630
Test Accuracy: 0.8983

## **Whether user will make more than 50k a year or not using single and multilayer neural**

## **Selecting Features**

In [100]:
# Define column names correctly (as lists of column names, not dataframes)
work_area_cols = ['job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management',
                  'job_retired', 'job_self-employed', 'job_services', 'job_student',
                  'job_technician', 'job_unemployed', 'job_unknown']

qualification_cols = ['education_secondary', 'education_tertiary', 'education_unknown']

marital_status_cols = ['marital_married', 'marital_single']

# Selecting relevant features from the dataframe
X = data[work_area_cols + qualification_cols + marital_status_cols]

# Target variable
y = data['y']

## **Spliting the dataset**

In [101]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

## **Scaling the Features**

In [102]:
Scaler=StandardScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.fit_transform(X_test)

## **Building the Recurrent neural network Model**

In [103]:
# Reshape for RNN input (samples, time_steps, features)
X_train_rnn = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_rnn = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

# Define the RNN model with a single neuron
model = Sequential([
    SimpleRNN(1, input_shape=(1, X_train_rnn.shape[2])),  # Correct input shape
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_rnn, y_train, epochs=50, batch_size=16, validation_data=(X_test_rnn, y_test))

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

198/198 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.5071 - loss: 0.6999 - val_accuracy: 0.6640 - val_loss: 0.6165
Epoch 2/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6878 - loss: 0.6025 - val_accuracy: 0.8165 - val_loss: 0.5371
Epoch 3/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8148 - loss: 0.5288 - val_accuracy: 0.8615 - val_loss: 0.4723
Epoch 4/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8633 - loss: 0.4533 - val_accuracy: 0.8644 - val_loss: 0.4221
Epoch 5/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8565 - loss: 0.4130 - val_accuracy: 0.8644 - val_loss: 0.3913
Epoch 6/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8570 - loss: 0.3896 - val_accuracy: 0.8644 - val_loss: 0.3753
Epoch 7/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8580 - loss: 0.3778 - val_accuracy: 0.8644 - val_loss: 0.3672
Epoch 8/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8449 - loss: 0.3875 - val_accuracy: 0.8644 - val_loss: 0.3622
Epoch 9/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3473 - val_accuracy: 0.8644 - val_loss: 0.3600
Epoch 10/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8578 - loss: 0.3623 - val_accuracy: 0.8644 - val_loss: 0.3581
Epoch 11/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8483 - loss: 0.3720 - val_accuracy: 0.8644 - val_loss: 0.3566
Epoch 12/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8645 - loss: 0.3481 - val_accuracy: 0.8644 - val_loss: 0.3555
Epoch 13/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8621 - loss: 0.3631 - val_accuracy: 0.8880 - val_loss: 0.3549
Epoch 14/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8879 - loss: 0.3517 - val_accuracy: 0.8880 - val_loss: 0.3544
Epoch 15/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8819 - loss: 0.3601 - val_accuracy: 0.8880 - val_loss: 0.3537
Epoch 16/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8771 - loss: 0.3658 - val_accuracy: 0.8880 - val_loss: 0.3531
Epoch 17/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8802 - loss: 0.3632 - val_accuracy: 0.8880 - val_loss: 0.3529
Epoch 18/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8836 - loss: 0.3544 - val_accuracy: 0.8880 - val_loss: 0.3525
Epoch 19/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8759 - loss: 0.3633 - val_accuracy: 0.8880 - val_loss: 0.3521
Epoch 20/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8885 - loss: 0.3461 - val_accuracy: 0.8880 - val_loss: 0.3518
Epoch 21/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8782 - loss: 0.3673 - val_accuracy: 0.8880 - val_loss: 0.3516
Epoch 22/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8911 - loss: 0.3363 - val_accuracy: 0.8880 - val_loss: 0.3514
Epoch 23/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8742 - loss: 0.3734 - val_accuracy: 0.8880 - val_loss: 0.3512
Epoch 24/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8865 - loss: 0.3513 - val_accuracy: 0.8880 - val_loss: 0.3509
Epoch 25/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8905 - loss: 0.3425 - val_accuracy: 0.8880 - val_loss: 0.3506
Epoch 26/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8784 - loss: 0.3635 - val_accuracy: 0.8880 - val_loss: 0.3506
Epoch 27/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8781 - loss: 0.3610 - val_accuracy: 0.8880 - val_loss: 0.3504
Epoch 28/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8704 - loss: 0.3767 - val_accuracy: 0.8880 - val_loss: 0.3503
Epoch 29/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8724 - loss: 0.3757 - val_accuracy: 0.8880 - val_loss: 0.3502
Epoch 30/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8862 - loss: 0.3435 - val_accuracy: 0.8880 - val_loss: 0.3501
Epoch 31/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8871 - loss: 0.3450 - val_accuracy: 0.8880 - val_loss: 0.3500
Epoch 32/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8820 - loss: 0.3583 - val_accuracy: 0.8880 - val_loss: 0.3499
Epoch 33/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8841 - loss: 0.3485 - val_accuracy: 0.8880 - val_loss: 0.3500
Epoch 34/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8802 - loss: 0.3583 - val_accuracy: 0.8880 - val_loss: 0.3499
Epoch 35/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8924 - loss: 0.3292 - val_accuracy: 0.8880 - val_loss: 0.3498
Epoch 36/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8872 - loss: 0.3430 - val_accuracy: 0.8880 - val_loss: 0.3499
Epoch 37/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8740 - loss: 0.3665 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 38/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8848 - loss: 0.3518 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 39/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8816 - loss: 0.3538 - val_accuracy: 0.8880 - val_loss: 0.3498
Epoch 40/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8772 - loss: 0.3646 - val_accuracy: 0.8880 - val_loss: 0.3496
Epoch 41/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8835 - loss: 0.3527 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 42/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8767 - loss: 0.3619 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 43/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8887 - loss: 0.3409 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 44/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8750 - loss: 0.3671 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 45/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8752 - loss: 0.3678 - val_accuracy: 0.8880 - val_loss: 0.3496
Epoch 46/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8834 - loss: 0.3531 - val_accuracy: 0.8880 - val_loss: 0.3496
Epoch 47/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8842 - loss: 0.3497 - val_accuracy: 0.8880 - val_loss: 0.3496
Epoch 48/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8870 - loss: 0.3421 - val_accuracy: 0.8880 - val_loss: 0.3497
Epoch 49/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8940 - loss: 0.3283 - val_accuracy: 0.8880 - val_loss: 0.3498
Epoch 50/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8813 - loss: 0.3575 - val_accuracy: 0.8880 - val_loss: 0.3497

## **Predictions**

In [104]:
# Make predictions
y_pred_prob = model.predict(X_test_rnn)

# Convert probabilities to binary labels (0 or 1)
y_pred = (y_pred_prob > 0.5).astype(int)

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

### **Prediction Output**

In [105]:
for i, prediction in enumerate(y_pred):
  print(f"customer {i+1} will {'subscribe' if prediction == 1 else 'not subscribe'} to subscription  ")

customer 1 will not subscribe to subscription
customer 2 will not subscribe to subscription
customer 3 will not subscribe to subscription
customer 4 will not subscribe to subscription
customer 5 will not subscribe to subscription
customer 6 will not subscribe to subscription
customer 7 will not subscribe to subscription
customer 8 will not subscribe to subscription
customer 9 will not subscribe to subscription
customer 10 will not subscribe to subscription
customer 11 will not subscribe to subscription
customer 12 will not subscribe to subscription
customer 13 will not subscribe to subscription
customer 14 will not subscribe to subscription
customer 15 will not subscribe to subscription
customer 16 will not subscribe to subscription
customer 17 will not subscribe to subscription
customer 18 will not subscribe to subscription
customer 19 will not subscribe to subscription
customer 20 will not subscribe to subscription
customer 21 will not subscribe to subscription
customer 22 will not subscribe to subscription
customer 23 will not subscribe to subscription
customer 24 will not subscribe to subscription
customer 25 will not subscribe to subscription
customer 26 will not subscribe to subscription
customer 27 will not subscribe to subscription
customer 28 will not subscribe to subscription
customer 29 will not subscribe to subscription
customer 30 will not subscribe to subscription
customer 31 will not subscribe to subscription
customer 32 will not subscribe to subscription
customer 33 will not subscribe to subscription
customer 34 will not subscribe to subscription
customer 35 will not subscribe to subscription
customer 36 will not subscribe to subscription
customer 37 will not subscribe to subscription
customer 38 will not subscribe to subscription
customer 39 will not subscribe to subscription
customer 40 will not subscribe to subscription
customer 41 will not subscribe to subscription
customer 42 will not subscribe to subscription
customer 43 will not subscribe to subscription
customer 44 will not subscribe to subscription
customer 45 will not subscribe to subscription
customer 46 will not subscribe to subscription
customer 47 will not subscribe to subscription
customer 48 will not subscribe to subscription
customer 49 will not subscribe to subscription
customer 50 will not subscribe to subscription
customer 51 will not subscribe to subscription
customer 52 will not subscribe to subscription
customer 53 will not subscribe to subscription
customer 54 will not subscribe to subscription
customer 55 will not subscribe to subscription
customer 56 will not subscribe to subscription
customer 57 will not subscribe to subscription
customer 58 will not subscribe to subscription
customer 59 will not subscribe to subscription
customer 60 will not subscribe to subscription
customer 61 will not subscribe to subscription
customer 62 will not subscribe to subscription
customer 63 will not subscribe to subscription
customer 64 will not subscribe to subscription
customer 65 will not subscribe to subscription
customer 66 will not subscribe to subscription
customer 67 will not subscribe to subscription
customer 68 will not subscribe to subscription
customer 69 will not subscribe to subscription
customer 70 will not subscribe to subscription
customer 71 will not subscribe to subscription
customer 72 will not subscribe to subscription
customer 73 will not subscribe to subscription
customer 74 will not subscribe to subscription
customer 75 will not subscribe to subscription
customer 76 will not subscribe to subscription
customer 77 will not subscribe to subscription
customer 78 will not subscribe to subscription
customer 79 will not subscribe to subscription
customer 80 will not subscribe to subscription
customer 81 will not subscribe to subscription
customer 82 will not subscribe to subscription
customer 83 will not subscribe to subscription
customer 84 will not subscribe to subscription
customer 85 will not subscribe to subscription
customer 86 will not subscribe to subscription
customer 87 will not subscribe to subscription
customer 88 will not subscribe to subscription
customer 89 will not subscribe to subscription
customer 90 will not subscribe to subscription
customer 91 will not subscribe to subscription
customer 92 will not subscribe to subscription
customer 93 will not subscribe to subscription
customer 94 will not subscribe to subscription
customer 95 will not subscribe to subscription
customer 96 will not subscribe to subscription
customer 97 will not subscribe to subscription
customer 98 will not subscribe to subscription
customer 99 will not subscribe to subscription
customer 100 will not subscribe to subscription
customer 101 will not subscribe to subscription
customer 102 will not subscribe to subscription
customer 103 will not subscribe to subscription
customer 104 will not subscribe to subscription
customer 105 will not subscribe to subscription
customer 106 will not subscribe to subscription
customer 107 will not subscribe to subscription
customer 108 will not subscribe to subscription
customer 109 will not subscribe to subscription
customer 110 will not subscribe to subscription
customer 111 will not subscribe to subscription
customer 112 will not subscribe to subscription
customer 113 will not subscribe to subscription
customer 114 will not subscribe to subscription
customer 115 will not subscribe to subscription
customer 116 will not subscribe to subscription
customer 117 will not subscribe to subscription
customer 118 will not subscribe to subscription
customer 119 will not subscribe to subscription
customer 120 will not subscribe to subscription
customer 121 will not subscribe to subscription
customer 122 will not subscribe to subscription
customer 123 will not subscribe to subscription
customer 124 will not subscribe to subscription
customer 125 will not subscribe to subscription
customer 126 will not subscribe to subscription
customer 127 will not subscribe to subscription
customer 128 will not subscribe to subscription
customer 129 will not subscribe to subscription
customer 130 will not subscribe to subscription
customer 131 will not subscribe to subscription
customer 132 will not subscribe to subscription
customer 133 will not subscribe to subscription
customer 134 will not subscribe to subscription
customer 135 will not subscribe to subscription
customer 136 will not subscribe to subscription
customer 137 will not subscribe to subscription
customer 138 will not subscribe to subscription
customer 139 will not subscribe to subscription
customer 140 will not subscribe to subscription
customer 141 will not subscribe to subscription
customer 142 will not subscribe to subscription
customer 143 will not subscribe to subscription
customer 144 will not subscribe to subscription
customer 145 will not subscribe to subscription
customer 146 will not subscribe to subscription
customer 147 will not subscribe to subscription
customer 148 will not subscribe to subscription
customer 149 will not subscribe to subscription
customer 150 will not subscribe to subscription
customer 151 will not subscribe to subscription
customer 152 will not subscribe to subscription
customer 153 will not subscribe to subscription
customer 154 will not subscribe to subscription
customer 155 will not subscribe to subscription
customer 156 will not subscribe to subscription
customer 157 will not subscribe to subscription
customer 158 will not subscribe to subscription
customer 159 will not subscribe to subscription
customer 160 will not subscribe to subscription
customer 161 will not subscribe to subscription
customer 162 will not subscribe to subscription
customer 163 will not subscribe to subscription
customer 164 will not subscribe to subscription
customer 165 will not subscribe to subscription
customer 166 will not subscribe to subscription
customer 167 will not subscribe to subscription
customer 168 will not subscribe to subscription
customer 169 will not subscribe to subscription
customer 170 will not subscribe to subscription
customer 171 will not subscribe to subscription
customer 172 will not subscribe to subscription
customer 173 will not subscribe to subscription
customer 174 will not subscribe to subscription
customer 175 will not subscribe to subscription
customer 176 will not subscribe to subscription
customer 177 will not subscribe to subscription
customer 178 will not subscribe to subscription
customer 179 will not subscribe to subscription
customer 180 will not subscribe to subscription
customer 181 will not subscribe to subscription
customer 182 will not subscribe to subscription
customer 183 will not subscribe to subscription
customer 184 will not subscribe to subscription
customer 185 will not subscribe to subscription
customer 186 will not subscribe to subscription
customer 187 will not subscribe to subscription
customer 188 will not subscribe to subscription
customer 189 will not subscribe to subscription
customer 190 will not subscribe to subscription
customer 191 will not subscribe to subscription
customer 192 will not subscribe to subscription
customer 193 will not subscribe to subscription
customer 194 will not subscribe to subscription
customer 195 will not subscribe to subscription
customer 196 will not subscribe to subscription
customer 197 will not subscribe to subscription
customer 198 will not subscribe to subscription
customer 199 will not subscribe to subscription
customer 200 will not subscribe to subscription
customer 201 will not subscribe to subscription
customer 202 will not subscribe to subscription
customer 203 will not subscribe to subscription
customer 204 will not subscribe to subscription
customer 205 will not subscribe to subscription
customer 206 will not subscribe to subscription
customer 207 will not subscribe to subscription
customer 208 will not subscribe to subscription
customer 209 will not subscribe to subscription
customer 210 will not subscribe to subscription
customer 211 will not subscribe to subscription
customer 212 will not subscribe to subscription
customer 213 will not subscribe to subscription
customer 214 will not subscribe to subscription
customer 215 will not subscribe to subscription
customer 216 will not subscribe to subscription
customer 217 will not subscribe to subscription
customer 218 will not subscribe to subscription
customer 219 will not subscribe to subscription
customer 220 will not subscribe to subscription
customer 221 will not subscribe to subscription
customer 222 will not subscribe to subscription
customer 223 will not subscribe to subscription
customer 224 will not subscribe to subscription
customer 225 will not subscribe to subscription
customer 226 will not subscribe to subscription
customer 227 will not subscribe to subscription
customer 228 will not subscribe to subscription
customer 229 will not subscribe to subscription
customer 230 will not subscribe to subscription
customer 231 will not subscribe to subscription
customer 232 will not subscribe to subscription
customer 233 will not subscribe to subscription
customer 234 will not subscribe to subscription
customer 235 will not subscribe to subscription
customer 236 will not subscribe to subscription
customer 237 will not subscribe to subscription
customer 238 will not subscribe to subscription
customer 239 will not subscribe to subscription
customer 240 will not subscribe to subscription
customer 241 will not subscribe to subscription
customer 242 will not subscribe to subscription
customer 243 will not subscribe to subscription
customer 244 will not subscribe to subscription
customer 245 will not subscribe to subscription
customer 246 will not subscribe to subscription
customer 247 will not subscribe to subscription
customer 248 will not subscribe to subscription
customer 249 will not subscribe to subscription
customer 250 will not subscribe to subscription
customer 251 will not subscribe to subscription
customer 252 will not subscribe to subscription
customer 253 will not subscribe to subscription
customer 254 will not subscribe to subscription
customer 255 will not subscribe to subscription
customer 256 will not subscribe to subscription
customer 257 will not subscribe to subscription
customer 258 will not subscribe to subscription
customer 259 will not subscribe to subscription
customer 260 will not subscribe to subscription
customer 261 will not subscribe to subscription
customer 262 will not subscribe to subscription
customer 263 will not subscribe to subscription
customer 264 will not subscribe to subscription
customer 265 will not subscribe to subscription
customer 266 will not subscribe to subscription
customer 267 will not subscribe to subscription
customer 268 will not subscribe to subscription
customer 269 will not subscribe to subscription
customer 270 will not subscribe to subscription
customer 271 will not subscribe to subscription
customer 272 will not subscribe to subscription
customer 273 will not subscribe to subscription
customer 274 will not subscribe to subscription
customer 275 will not subscribe to subscription
customer 276 will not subscribe to subscription
customer 277 will not subscribe to subscription
customer 278 will not subscribe to subscription
customer 279 will not subscribe to subscription
customer 280 will not subscribe to subscription
customer 281 will not subscribe to subscription
customer 282 will not subscribe to subscription
customer 283 will not subscribe to subscription
customer 284 will not subscribe to subscription
customer 285 will not subscribe to subscription
customer 286 will not subscribe to subscription
customer 287 will not subscribe to subscription
customer 288 will not subscribe to subscription
customer 289 will not subscribe to subscription
customer 290 will not subscribe to subscription
customer 291 will not subscribe to subscription
customer 292 will not subscribe to subscription
customer 293 will not subscribe to subscription
customer 294 will not subscribe to subscription
customer 295 will not subscribe to subscription
customer 296 will not subscribe to subscription
customer 297 will not subscribe to subscription
customer 298 will not subscribe to subscription
customer 299 will not subscribe to subscription
customer 300 will not subscribe to subscription
customer 301 will not subscribe to subscription
customer 302 will not subscribe to subscription
customer 303 will not subscribe to subscription
customer 304 will not subscribe to subscription
customer 305 will not subscribe to subscription
customer 306 will not subscribe to subscription
customer 307 will not subscribe to subscription
customer 308 will not subscribe to subscription
customer 309 will not subscribe to subscription
customer 310 will not subscribe to subscription
customer 311 will not subscribe to subscription
customer 312 will not subscribe to subscription
customer 313 will not subscribe to subscription
customer 314 will not subscribe to subscription
customer 315 will not subscribe to subscription
customer 316 will not subscribe to subscription
customer 317 will not subscribe to subscription
customer 318 will not subscribe to subscription
customer 319 will not subscribe to subscription
customer 320 will not subscribe to subscription
customer 321 will not subscribe to subscription
customer 322 will not subscribe to subscription
customer 323 will not subscribe to subscription
customer 324 will not subscribe to subscription
customer 325 will not subscribe to subscription
customer 326 will not subscribe to subscription
customer 327 will not subscribe to subscription
customer 328 will not subscribe to subscription
customer 329 will not subscribe to subscription
customer 330 will not subscribe to subscription
customer 331 will not subscribe to subscription
customer 332 will not subscribe to subscription
customer 333 will not subscribe to subscription
customer 334 will not subscribe to subscription
customer 335 will not subscribe to subscription
customer 336 will not subscribe to subscription
customer 337 will not subscribe to subscription
customer 338 will not subscribe to subscription
customer 339 will not subscribe to subscription
customer 340 will not subscribe to subscription
customer 341 will not subscribe to subscription
customer 342 will not subscribe to subscription
customer 343 will not subscribe to subscription
customer 344 will not subscribe to subscription
customer 345 will not subscribe to subscription
customer 346 will not subscribe to subscription
customer 347 will not subscribe to subscription
customer 348 will not subscribe to subscription
customer 349 will not subscribe to subscription
customer 350 will not subscribe to subscription
customer 351 will not subscribe to subscription
customer 352 will not subscribe to subscription
customer 353 will not subscribe to subscription
customer 354 will not subscribe to subscription
customer 355 will not subscribe to subscription
customer 356 will not subscribe to subscription
customer 357 will not subscribe to subscription
customer 358 will not subscribe to subscription
customer 359 will not subscribe to subscription
customer 360 will not subscribe to subscription
customer 361 will not subscribe to subscription
customer 362 will not subscribe to subscription
customer 363 will not subscribe to subscription
customer 364 will not subscribe to subscription
customer 365 will not subscribe to subscription
customer 366 will not subscribe to subscription
customer 367 will not subscribe to subscription
customer 368 will not subscribe to subscription
customer 369 will not subscribe to subscription
customer 370 will not subscribe to subscription
customer 371 will not subscribe to subscription
customer 372 will not subscribe to subscription
customer 373 will not subscribe to subscription
customer 374 will not subscribe to subscription
customer 375 will not subscribe to subscription
customer 376 will not subscribe to subscription
customer 377 will not subscribe to subscription
customer 378 will not subscribe to subscription
customer 379 will not subscribe to subscription
customer 380 will not subscribe to subscription
customer 381 will not subscribe to subscription
customer 382 will not subscribe to subscription
customer 383 will not subscribe to subscription
customer 384 will not subscribe to subscription
customer 385 will not subscribe to subscription
customer 386 will not subscribe to subscription
customer 387 will not subscribe to subscription
customer 388 will not subscribe to subscription
customer 389 will not subscribe to subscription
customer 390 will not subscribe to subscription
customer 391 will not subscribe to subscription
customer 392 will not subscribe to subscription
customer 393 will not subscribe to subscription
customer 394 will not subscribe to subscription
customer 395 will not subscribe to subscription
customer 396 will not subscribe to subscription
customer 397 will not subscribe to subscription
customer 398 will not subscribe to subscription
customer 399 will not subscribe to subscription
customer 400 will not subscribe to subscription
customer 401 will not subscribe to subscription
customer 402 will not subscribe to subscription
customer 403 will not subscribe to subscription
customer 404 will not subscribe to subscription
customer 405 will not subscribe to subscription
customer 406 will not subscribe to subscription
customer 407 will not subscribe to subscription
customer 408 will not subscribe to subscription
customer 409 will not subscribe to subscription
customer 410 will not subscribe to subscription
customer 411 will not subscribe to subscription
customer 412 will not subscribe to subscription
customer 413 will not subscribe to subscription
customer 414 will not subscribe to subscription
customer 415 will not subscribe to subscription
customer 416 will not subscribe to subscription
customer 417 will not subscribe to subscription
customer 418 will not subscribe to subscription

## **Number of People will be able to make more than 50K a year**

In [106]:
count_able = 0
count_unable=0

for prediction in y_pred:
  if prediction ==1 :
    count_able +=1
  else:
    count_unable +=1

print(f'No. of customer able to subscribe {count_able}')

print(f'No. of customer not able to subscribe {count_unable}')

No. of customer able to subscribe 0
No. of customer not able to subscribe 1357

# **Evaluate  Model**

In [107]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test_rnn, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8899 - loss: 0.3445
Test Accuracy: 0.8880

## **Multi layers neuron**

## **Selecting Features**

In [108]:
# Define column names correctly (as lists of column names, not dataframes)
work_area_cols = ['job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management',
                  'job_retired', 'job_self-employed', 'job_services', 'job_student',
                  'job_technician', 'job_unemployed', 'job_unknown']

qualification_cols = ['education_secondary', 'education_tertiary', 'education_unknown']

marital_status_cols = ['marital_married', 'marital_single']

# Selecting relevant features from the dataframe
X = data[work_area_cols + qualification_cols + marital_status_cols]

# Target variable
y = data['y']

# **Spliting Dataset**

In [109]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

# **Scaling Dataset**

In [110]:
Scaler=StandardScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.fit_transform(X_test)

# **Building Neural Network**

In [111]:
# Reshape for RNN input (samples, time_steps, features)
X_train_rnn = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_rnn = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

# Define the Multi-Layer RNN Model
model = Sequential([
    SimpleRNN(32, return_sequences=True, input_shape=(1, X_train_rnn.shape[2])),  # First RNN Layer
    SimpleRNN(16, return_sequences=False),  # Second RNN Layer
    Dense(4, activation='relu'),  # Fully Connected Hidden Layer
    Dense(1, activation='sigmoid')  # Output Layer for Binary Classification
])

# Compile the Model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the Model
history = model.fit(X_train_rnn, y_train, epochs=50, batch_size=16, validation_data=(X_test_rnn, y_test))

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

198/198 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7651 - loss: 0.6116 - val_accuracy: 0.8880 - val_loss: 0.3800
Epoch 2/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8887 - loss: 0.3548 - val_accuracy: 0.8880 - val_loss: 0.3530
Epoch 3/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8709 - loss: 0.3699 - val_accuracy: 0.8880 - val_loss: 0.3501
Epoch 4/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8790 - loss: 0.3610 - val_accuracy: 0.8880 - val_loss: 0.3502
Epoch 5/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8891 - loss: 0.3390 - val_accuracy: 0.8873 - val_loss: 0.3501
Epoch 6/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8787 - loss: 0.3585 - val_accuracy: 0.8865 - val_loss: 0.3505
Epoch 7/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8779 - loss: 0.3562 - val_accuracy: 0.8865 - val_loss: 0.3498
Epoch 8/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8839 - loss: 0.3442 - val_accuracy: 0.8865 - val_loss: 0.3502
Epoch 9/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8840 - loss: 0.3427 - val_accuracy: 0.8865 - val_loss: 0.3502
Epoch 10/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8795 - loss: 0.3530 - val_accuracy: 0.8865 - val_loss: 0.3504
Epoch 11/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8808 - loss: 0.3533 - val_accuracy: 0.8865 - val_loss: 0.3510
Epoch 12/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8822 - loss: 0.3449 - val_accuracy: 0.8865 - val_loss: 0.3508
Epoch 13/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8863 - loss: 0.3414 - val_accuracy: 0.8865 - val_loss: 0.3511
Epoch 14/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8792 - loss: 0.3411 - val_accuracy: 0.8865 - val_loss: 0.3511
Epoch 15/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8824 - loss: 0.3413 - val_accuracy: 0.8865 - val_loss: 0.3518
Epoch 16/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8811 - loss: 0.3453 - val_accuracy: 0.8865 - val_loss: 0.3503
Epoch 17/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8756 - loss: 0.3548 - val_accuracy: 0.8865 - val_loss: 0.3514
Epoch 18/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8861 - loss: 0.3413 - val_accuracy: 0.8865 - val_loss: 0.3512
Epoch 19/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8784 - loss: 0.3529 - val_accuracy: 0.8865 - val_loss: 0.3505
Epoch 20/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8831 - loss: 0.3427 - val_accuracy: 0.8865 - val_loss: 0.3520
Epoch 21/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8896 - loss: 0.3233 - val_accuracy: 0.8865 - val_loss: 0.3512
Epoch 22/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8851 - loss: 0.3352 - val_accuracy: 0.8865 - val_loss: 0.3517
Epoch 23/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8767 - loss: 0.3532 - val_accuracy: 0.8865 - val_loss: 0.3521
Epoch 24/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8796 - loss: 0.3499 - val_accuracy: 0.8865 - val_loss: 0.3522
Epoch 25/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8827 - loss: 0.3454 - val_accuracy: 0.8865 - val_loss: 0.3520
Epoch 26/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8839 - loss: 0.3410 - val_accuracy: 0.8865 - val_loss: 0.3531
Epoch 27/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8830 - loss: 0.3311 - val_accuracy: 0.8865 - val_loss: 0.3523
Epoch 28/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8861 - loss: 0.3343 - val_accuracy: 0.8843 - val_loss: 0.3530
Epoch 29/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8743 - loss: 0.3534 - val_accuracy: 0.8865 - val_loss: 0.3531
Epoch 30/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8688 - loss: 0.3567 - val_accuracy: 0.8865 - val_loss: 0.3522
Epoch 31/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8866 - loss: 0.3312 - val_accuracy: 0.8858 - val_loss: 0.3522
Epoch 32/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8967 - loss: 0.3146 - val_accuracy: 0.8865 - val_loss: 0.3537
Epoch 33/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8712 - loss: 0.3602 - val_accuracy: 0.8865 - val_loss: 0.3529
Epoch 34/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8831 - loss: 0.3377 - val_accuracy: 0.8865 - val_loss: 0.3530
Epoch 35/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8834 - loss: 0.3474 - val_accuracy: 0.8865 - val_loss: 0.3538
Epoch 36/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8861 - loss: 0.3235 - val_accuracy: 0.8858 - val_loss: 0.3531
Epoch 37/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8909 - loss: 0.3230 - val_accuracy: 0.8865 - val_loss: 0.3544
Epoch 38/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8826 - loss: 0.3408 - val_accuracy: 0.8865 - val_loss: 0.3540
Epoch 39/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8887 - loss: 0.3273 - val_accuracy: 0.8865 - val_loss: 0.3538
Epoch 40/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8734 - loss: 0.3604 - val_accuracy: 0.8865 - val_loss: 0.3546
Epoch 41/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8840 - loss: 0.3430 - val_accuracy: 0.8843 - val_loss: 0.3550
Epoch 42/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8754 - loss: 0.3504 - val_accuracy: 0.8858 - val_loss: 0.3527
Epoch 43/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8787 - loss: 0.3491 - val_accuracy: 0.8865 - val_loss: 0.3543
Epoch 44/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8761 - loss: 0.3531 - val_accuracy: 0.8865 - val_loss: 0.3537
Epoch 45/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8835 - loss: 0.3296 - val_accuracy: 0.8865 - val_loss: 0.3543
Epoch 46/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8903 - loss: 0.3227 - val_accuracy: 0.8865 - val_loss: 0.3546
Epoch 47/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8738 - loss: 0.3597 - val_accuracy: 0.8865 - val_loss: 0.3552
Epoch 48/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8901 - loss: 0.3184 - val_accuracy: 0.8858 - val_loss: 0.3546
Epoch 49/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8981 - loss: 0.3157 - val_accuracy: 0.8865 - val_loss: 0.3561
Epoch 50/50
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8840 - loss: 0.3403 - val_accuracy: 0.8843 - val_loss: 0.3548

## **Predictions**

In [112]:
# Make predictions
y_pred_prob = model.predict(X_test_rnn)

# Convert probabilities to binary labels (0 or 1)
y_pred = (y_pred_prob > 0.5).astype(int)

43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

## **Prediction**

In [113]:
for i, prediction in enumerate(y_pred):
    print(f'Customer {i+1} will {"be able" if prediction == 1 else "not be able"} to make more than 50k a year.')

Customer 1 will not be able to make more than 50k a year.
Customer 2 will not be able to make more than 50k a year.
Customer 3 will not be able to make more than 50k a year.
Customer 4 will not be able to make more than 50k a year.
Customer 5 will not be able to make more than 50k a year.
Customer 6 will not be able to make more than 50k a year.
Customer 7 will not be able to make more than 50k a year.
Customer 8 will not be able to make more than 50k a year.
Customer 9 will not be able to make more than 50k a year.
Customer 10 will not be able to make more than 50k a year.
Customer 11 will not be able to make more than 50k a year.
Customer 12 will not be able to make more than 50k a year.
Customer 13 will not be able to make more than 50k a year.
Customer 14 will be able to make more than 50k a year.
Customer 15 will not be able to make more than 50k a year.
Customer 16 will not be able to make more than 50k a year.
Customer 17 will not be able to make more than 50k a year.
Customer 18 will not be able to make more than 50k a year.
Customer 19 will not be able to make more than 50k a year.
Customer 20 will not be able to make more than 50k a year.
Customer 21 will not be able to make more than 50k a year.
Customer 22 will not be able to make more than 50k a year.
Customer 23 will not be able to make more than 50k a year.
Customer 24 will not be able to make more than 50k a year.
Customer 25 will not be able to make more than 50k a year.
Customer 26 will not be able to make more than 50k a year.
Customer 27 will not be able to make more than 50k a year.
Customer 28 will not be able to make more than 50k a year.
Customer 29 will not be able to make more than 50k a year.
Customer 30 will not be able to make more than 50k a year.
Customer 31 will not be able to make more than 50k a year.
Customer 32 will not be able to make more than 50k a year.
Customer 33 will not be able to make more than 50k a year.
Customer 34 will not be able to make more than 50k a year.
Customer 35 will not be able to make more than 50k a year.
Customer 36 will not be able to make more than 50k a year.
Customer 37 will not be able to make more than 50k a year.
Customer 38 will not be able to make more than 50k a year.
Customer 39 will not be able to make more than 50k a year.
Customer 40 will not be able to make more than 50k a year.
Customer 41 will not be able to make more than 50k a year.
Customer 42 will not be able to make more than 50k a year.
Customer 43 will not be able to make more than 50k a year.
Customer 44 will not be able to make more than 50k a year.
Customer 45 will not be able to make more than 50k a year.
Customer 46 will not be able to make more than 50k a year.
Customer 47 will not be able to make more than 50k a year.
Customer 48 will not be able to make more than 50k a year.
Customer 49 will not be able to make more than 50k a year.
Customer 50 will not be able to make more than 50k a year.
Customer 51 will not be able to make more than 50k a year.
Customer 52 will not be able to make more than 50k a year.
Customer 53 will not be able to make more than 50k a year.
Customer 54 will not be able to make more than 50k a year.
Customer 55 will not be able to make more than 50k a year.
Customer 56 will not be able to make more than 50k a year.
Customer 57 will not be able to make more than 50k a year.
Customer 58 will not be able to make more than 50k a year.
Customer 59 will not be able to make more than 50k a year.
Customer 60 will not be able to make more than 50k a year.
Customer 61 will not be able to make more than 50k a year.
Customer 62 will not be able to make more than 50k a year.
Customer 63 will not be able to make more than 50k a year.
Customer 64 will not be able to make more than 50k a year.
Customer 65 will not be able to make more than 50k a year.
Customer 66 will not be able to make more than 50k a year.
Customer 67 will not be able to make more than 50k a year.
Customer 68 will not be able to make more than 50k a year.
Customer 69 will not be able to make more than 50k a year.
Customer 70 will not be able to make more than 50k a year.
Customer 71 will not be able to make more than 50k a year.
Customer 72 will not be able to make more than 50k a year.
Customer 73 will not be able to make more than 50k a year.
Customer 74 will not be able to make more than 50k a year.
Customer 75 will be able to make more than 50k a year.
Customer 76 will not be able to make more than 50k a year.
Customer 77 will not be able to make more than 50k a year.
Customer 78 will not be able to make more than 50k a year.
Customer 79 will not be able to make more than 50k a year.
Customer 80 will not be able to make more than 50k a year.
Customer 81 will not be able to make more than 50k a year.
Customer 82 will not be able to make more than 50k a year.
Customer 83 will not be able to make more than 50k a year.
Customer 84 will not be able to make more than 50k a year.
Customer 85 will not be able to make more than 50k a year.
Customer 86 will not be able to make more than 50k a year.
Customer 87 will not be able to make more than 50k a year.
Customer 88 will not be able to make more than 50k a year.
Customer 89 will not be able to make more than 50k a year.
Customer 90 will not be able to make more than 50k a year.
Customer 91 will not be able to make more than 50k a year.
Customer 92 will not be able to make more than 50k a year.
Customer 93 will not be able to make more than 50k a year.
Customer 94 will not be able to make more than 50k a year.
Customer 95 will not be able to make more than 50k a year.
Customer 96 will not be able to make more than 50k a year.
Customer 97 will not be able to make more than 50k a year.
Customer 98 will not be able to make more than 50k a year.
Customer 99 will not be able to make more than 50k a year.
Customer 100 will not be able to make more than 50k a year.
Customer 101 will not be able to make more than 50k a year.
Customer 102 will not be able to make more than 50k a year.
Customer 103 will not be able to make more than 50k a year.
Customer 104 will not be able to make more than 50k a year.
Customer 105 will not be able to make more than 50k a year.
Customer 106 will not be able to make more than 50k a year.
Customer 107 will not be able to make more than 50k a year.
Customer 108 will not be able to make more than 50k a year.
Customer 109 will not be able to make more than 50k a year.
Customer 110 will not be able to make more than 50k a year.
Customer 111 will not be able to make more than 50k a year.
Customer 112 will not be able to make more than 50k a year.
Customer 113 will not be able to make more than 50k a year.
Customer 114 will not be able to make more than 50k a year.
Customer 115 will not be able to make more than 50k a year.
Customer 116 will not be able to make more than 50k a year.
Customer 117 will not be able to make more than 50k a year.
Customer 118 will not be able to make more than 50k a year.
Customer 119 will not be able to make more than 50k a year.
Customer 120 will not be able to make more than 50k a year.
Customer 121 will not be able to make more than 50k a year.
Customer 122 will not be able to make more than 50k a year.
Customer 123 will not be able to make more than 50k a year.
Customer 124 will not be able to make more than 50k a year.
Customer 125 will not be able to make more than 50k a year.
Customer 126 will not be able to make more than 50k a year.
Customer 127 will not be able to make more than 50k a year.
Customer 128 will not be able to make more than 50k a year.
Customer 129 will not be able to make more than 50k a year.
Customer 130 will not be able to make more than 50k a year.
Customer 131 will not be able to make more than 50k a year.
Customer 132 will not be able to make more than 50k a year.
Customer 133 will not be able to make more than 50k a year.
Customer 134 will not be able to make more than 50k a year.
Customer 135 will not be able to make more than 50k a year.
Customer 136 will not be able to make more than 50k a year.
Customer 137 will not be able to make more than 50k a year.
Customer 138 will not be able to make more than 50k a year.
Customer 139 will not be able to make more than 50k a year.
Customer 140 will not be able to make more than 50k a year.
Customer 141 will not be able to make more than 50k a year.
Customer 142 will not be able to make more than 50k a year.
Customer 143 will not be able to make more than 50k a year.
Customer 144 will not be able to make more than 50k a year.
Customer 145 will not be able to make more than 50k a year.
Customer 146 will not be able to make more than 50k a year.
Customer 147 will not be able to make more than 50k a year.
Customer 148 will not be able to make more than 50k a year.
Customer 149 will not be able to make more than 50k a year.
Customer 150 will not be able to make more than 50k a year.
Customer 151 will not be able to make more than 50k a year.
Customer 152 will not be able to make more than 50k a year.
Customer 153 will not be able to make more than 50k a year.
Customer 154 will not be able to make more than 50k a year.
Customer 155 will not be able to make more than 50k a year.
Customer 156 will not be able to make more than 50k a year.
Customer 157 will not be able to make more than 50k a year.
Customer 158 will not be able to make more than 50k a year.
Customer 159 will not be able to make more than 50k a year.
Customer 160 will not be able to make more than 50k a year.
Customer 161 will not be able to make more than 50k a year.
Customer 162 will not be able to make more than 50k a year.
Customer 163 will not be able to make more than 50k a year.
Customer 164 will not be able to make more than 50k a year.
Customer 165 will not be able to make more than 50k a year.
Customer 166 will not be able to make more than 50k a year.
Customer 167 will not be able to make more than 50k a year.
Customer 168 will not be able to make more than 50k a year.
Customer 169 will not be able to make more than 50k a year.
Customer 170 will not be able to make more than 50k a year.
Customer 171 will not be able to make more than 50k a year.
Customer 172 will not be able to make more than 50k a year.
Customer 173 will not be able to make more than 50k a year.
Customer 174 will not be able to make more than 50k a year.
Customer 175 will not be able to make more than 50k a year.
Customer 176 will not be able to make more than 50k a year.
Customer 177 will not be able to make more than 50k a year.
Customer 178 will not be able to make more than 50k a year.
Customer 179 will not be able to make more than 50k a year.
Customer 180 will not be able to make more than 50k a year.
Customer 181 will not be able to make more than 50k a year.
Customer 182 will not be able to make more than 50k a year.
Customer 183 will not be able to make more than 50k a year.
Customer 184 will not be able to make more than 50k a year.
Customer 185 will not be able to make more than 50k a year.
Customer 186 will not be able to make more than 50k a year.
Customer 187 will not be able to make more than 50k a year.
Customer 188 will not be able to make more than 50k a year.
Customer 189 will not be able to make more than 50k a year.
Customer 190 will not be able to make more than 50k a year.
Customer 191 will not be able to make more than 50k a year.
Customer 192 will not be able to make more than 50k a year.
Customer 193 will not be able to make more than 50k a year.
Customer 194 will not be able to make more than 50k a year.
Customer 195 will not be able to make more than 50k a year.
Customer 196 will not be able to make more than 50k a year.
Customer 197 will not be able to make more than 50k a year.
Customer 198 will not be able to make more than 50k a year.
Customer 199 will not be able to make more than 50k a year.
Customer 200 will be able to make more than 50k a year.
Customer 201 will not be able to make more than 50k a year.
Customer 202 will not be able to make more than 50k a year.
Customer 203 will not be able to make more than 50k a year.
Customer 204 will not be able to make more than 50k a year.
Customer 205 will not be able to make more than 50k a year.
Customer 206 will not be able to make more than 50k a year.
Customer 207 will not be able to make more than 50k a year.
Customer 208 will not be able to make more than 50k a year.
Customer 209 will not be able to make more than 50k a year.
Customer 210 will not be able to make more than 50k a year.
Customer 211 will not be able to make more than 50k a year.
Customer 212 will not be able to make more than 50k a year.
Customer 213 will not be able to make more than 50k a year.
Customer 214 will not be able to make more than 50k a year.
Customer 215 will not be able to make more than 50k a year.
Customer 216 will not be able to make more than 50k a year.
Customer 217 will not be able to make more than 50k a year.
Customer 218 will not be able to make more than 50k a year.
Customer 219 will not be able to make more than 50k a year.
Customer 220 will not be able to make more than 50k a year.
Customer 221 will not be able to make more than 50k a year.
Customer 222 will not be able to make more than 50k a year.
Customer 223 will not be able to make more than 50k a year.
Customer 224 will not be able to make more than 50k a year.
Customer 225 will not be able to make more than 50k a year.
Customer 226 will not be able to make more than 50k a year.
Customer 227 will not be able to make more than 50k a year.
Customer 228 will not be able to make more than 50k a year.
Customer 229 will not be able to make more than 50k a year.
Customer 230 will not be able to make more than 50k a year.
Customer 231 will not be able to make more than 50k a year.
Customer 232 will not be able to make more than 50k a year.
Customer 233 will not be able to make more than 50k a year.
Customer 234 will not be able to make more than 50k a year.
Customer 235 will not be able to make more than 50k a year.
Customer 236 will not be able to make more than 50k a year.
Customer 237 will not be able to make more than 50k a year.
Customer 238 will not be able to make more than 50k a year.
Customer 239 will not be able to make more than 50k a year.
Customer 240 will not be able to make more than 50k a year.
Customer 241 will not be able to make more than 50k a year.
Customer 242 will not be able to make more than 50k a year.
Customer 243 will not be able to make more than 50k a year.
Customer 244 will not be able to make more than 50k a year.
Customer 245 will not be able to make more than 50k a year.
Customer 246 will not be able to make more than 50k a year.
Customer 247 will not be able to make more than 50k a year.
Customer 248 will not be able to make more than 50k a year.
Customer 249 will not be able to make more than 50k a year.
Customer 250 will not be able to make more than 50k a year.
Customer 251 will not be able to make more than 50k a year.
Customer 252 will not be able to make more than 50k a year.
Customer 253 will not be able to make more than 50k a year.
Customer 254 will not be able to make more than 50k a year.
Customer 255 will not be able to make more than 50k a year.
Customer 256 will not be able to make more than 50k a year.
Customer 257 will not be able to make more than 50k a year.
Customer 258 will not be able to make more than 50k a year.
Customer 259 will not be able to make more than 50k a year.
Customer 260 will not be able to make more than 50k a year.
Customer 261 will not be able to make more than 50k a year.
Customer 262 will not be able to make more than 50k a year.
Customer 263 will not be able to make more than 50k a year.
Customer 264 will not be able to make more than 50k a year.
Customer 265 will not be able to make more than 50k a year.
Customer 266 will not be able to make more than 50k a year.
Customer 267 will not be able to make more than 50k a year.
Customer 268 will not be able to make more than 50k a year.
Customer 269 will not be able to make more than 50k a year.
Customer 270 will not be able to make more than 50k a year.
Customer 271 will not be able to make more than 50k a year.
Customer 272 will not be able to make more than 50k a year.
Customer 273 will not be able to make more than 50k a year.
Customer 274 will not be able to make more than 50k a year.
Customer 275 will not be able to make more than 50k a year.
Customer 276 will not be able to make more than 50k a year.
Customer 277 will not be able to make more than 50k a year.
Customer 278 will not be able to make more than 50k a year.
Customer 279 will not be able to make more than 50k a year.
Customer 280 will not be able to make more than 50k a year.
Customer 281 will not be able to make more than 50k a year.
Customer 282 will not be able to make more than 50k a year.
Customer 283 will not be able to make more than 50k a year.
Customer 284 will not be able to make more than 50k a year.
Customer 285 will not be able to make more than 50k a year.
Customer 286 will not be able to make more than 50k a year.
Customer 287 will not be able to make more than 50k a year.
Customer 288 will not be able to make more than 50k a year.
Customer 289 will not be able to make more than 50k a year.
Customer 290 will not be able to make more than 50k a year.
Customer 291 will not be able to make more than 50k a year.
Customer 292 will not be able to make more than 50k a year.
Customer 293 will not be able to make more than 50k a year.
Customer 294 will not be able to make more than 50k a year.
Customer 295 will not be able to make more than 50k a year.
Customer 296 will not be able to make more than 50k a year.
Customer 297 will not be able to make more than 50k a year.
Customer 298 will not be able to make more than 50k a year.
Customer 299 will not be able to make more than 50k a year.
Customer 300 will not be able to make more than 50k a year.
Customer 301 will not be able to make more than 50k a year.
Customer 302 will not be able to make more than 50k a year.
Customer 303 will not be able to make more than 50k a year.
Customer 304 will not be able to make more than 50k a year.
Customer 305 will not be able to make more than 50k a year.
Customer 306 will not be able to make more than 50k a year.
Customer 307 will not be able to make more than 50k a year.
Customer 308 will not be able to make more than 50k a year.
Customer 309 will not be able to make more than 50k a year.
Customer 310 will not be able to make more than 50k a year.
Customer 311 will not be able to make more than 50k a year.
Customer 312 will not be able to make more than 50k a year.
Customer 313 will not be able to make more than 50k a year.
Customer 314 will not be able to make more than 50k a year.
Customer 315 will not be able to make more than 50k a year.
Customer 316 will not be able to make more than 50k a year.
Customer 317 will not be able to make more than 50k a year.
Customer 318 will not be able to make more than 50k a year.
Customer 319 will not be able to make more than 50k a year.
Customer 320 will not be able to make more than 50k a year.
Customer 321 will not be able to make more than 50k a year.
Customer 322 will not be able to make more than 50k a year.
Customer 323 will not be able to make more than 50k a year.
Customer 324 will not be able to make more than 50k a year.
Customer 325 will not be able to make more than 50k a year.
Customer 326 will not be able to make more than 50k a year.
Customer 327 will not be able to make more than 50k a year.
Customer 328 will not be able to make more than 50k a year.
Customer 329 will not be able to make more than 50k a year.
Customer 330 will not be able to make more than 50k a year.
Customer 331 will not be able to make more than 50k a year.
Customer 332 will not be able to make more than 50k a year.
Customer 333 will not be able to make more than 50k a year.
Customer 334 will not be able to make more than 50k a year.
Customer 335 will not be able to make more than 50k a year.

#**Number of People will be able to make more than 50K a year**

In [114]:
count_able = 0
count_unable=0

for prediction in y_pred:
  if prediction ==1 :
    count_able +=1
  else:
    count_unable +=1

print(f'No. of customer able to subscribe {count_able}')

print(f'No. of customer not able to subscribe {count_unable}')

No. of customer able to subscribe 13
No. of customer not able to subscribe 1344

# **Evaluate  Model**

In [115]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test_rnn, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8838 - loss: 0.3543
Test Accuracy: 0.8843