## **Unsupervised Learing**
## **K-NN Algorithm**

## **Upload the the dataset**

In [1]:
from google.colab import files
uploaded =files.upload()

Saving bank.csv to bank.csv

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_selection import SelectKBest, f_classif

## **Reading a dataset**

In [3]:
data=pd.read_csv('bank.csv',sep=';')

## **Data Head**

In [4]:
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

## **Data Information**

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

## **Checking for missing data records**

In [6]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

### **Checking for ducplicate data**

In [7]:
data.duplicated().sum()

0

## **Getting to know the unique values in categorical columns**

In [8]:
print(f"Various Job Categories in dataset :{data['job'].unique()}")

print(f"Various Marital Status in dataset:{data['marital'].unique()}")

print(f"Various education Status in dataset:{data['education'].unique()}")

print(f"Various defalut Status in dataset:{data['default'].unique()}")

print(f"Various housing Status in dataset:{data['housing'].unique()}")

print(f"Various loan status in dataset:{data['loan'].unique()}")

print(f"Various contact status in dataset:{data['contact'].unique()}")

print(f"Various month status in dataset:{data['month'].unique()}")

print(f"Various poutcome status in dataset:{data['poutcome'].unique()}")

Various Job Categories in dataset :['unemployed' 'services' 'management' 'blue-collar' 'self-employed'
 'technician' 'entrepreneur' 'admin.' 'student' 'housemaid' 'retired'
 'unknown']
Various Marital Status in dataset:['married' 'single' 'divorced']
Various education Status in dataset:['primary' 'secondary' 'tertiary' 'unknown']
Various defalut Status in dataset:['no' 'yes']
Various housing Status in dataset:['no' 'yes']
Various loan status in dataset:['no' 'yes']
Various contact status in dataset:['cellular' 'unknown' 'telephone']
Various month status in dataset:['oct' 'may' 'apr' 'jun' 'feb' 'aug' 'jan' 'jul' 'nov' 'sep' 'mar' 'dec']
Various poutcome status in dataset:['unknown' 'failure' 'other' 'success']

## **Converting the categorial Data to numberical using labeling for binary columns and one-hot-coding for multile label category**

In [9]:
#Labeling binary columns
binary_col=['default','housing','loan','y']

for col in binary_col:
  data[col]=data[col].map({'no':0, 'yes':1})

In [10]:
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,0,1787,0,0,cellular,19,oct,79,1,-1,0,unknown,0
1,33,services,married,secondary,0,4789,1,1,cellular,11,may,220,1,339,4,failure,0
2,35,management,single,tertiary,0,1350,1,0,cellular,16,apr,185,1,330,1,failure,0
3,30,management,married,tertiary,0,1476,1,1,unknown,3,jun,199,4,-1,0,unknown,0
4,59,blue-collar,married,secondary,0,0,1,0,unknown,5,may,226,1,-1,0,unknown,0

In [11]:
#Labeling Multi class column using One-Hot-Coding
multi_class_columns=['job','marital','education','contact','month','poutcome']

df_encoded = pd.get_dummies(data, columns=multi_class_columns, drop_first=True)
data = df_encoded.astype(int)

In [12]:
data.head()

,age,default,balance,housing,loan,day,duration,campaign,pdays,previous,...,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_other,poutcome_success,poutcome_unknown
0,30,0,1787,0,0,19,79,1,-1,0,...,0,0,0,0,0,1,0,0,0,1
1,33,0,4789,1,1,11,220,1,339,4,...,0,0,0,1,0,0,0,0,0,0
2,35,0,1350,1,0,16,185,1,330,1,...,0,0,0,0,0,0,0,0,0,0
3,30,0,1476,1,1,3,199,4,-1,0,...,0,1,0,0,0,0,0,0,0,1
4,59,0,0,1,0,5,226,1,-1,0,...,0,0,0,1,0,0,0,0,0,1

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  4521 non-null   int64
 1   default              4521 non-null   int64
 2   balance              4521 non-null   int64
 3   housing              4521 non-null   int64
 4   loan                 4521 non-null   int64
 5   day                  4521 non-null   int64
 6   duration             4521 non-null   int64
 7   campaign             4521 non-null   int64
 8   pdays                4521 non-null   int64
 9   previous             4521 non-null   int64
 10  y                    4521 non-null   int64
 11  job_blue-collar      4521 non-null   int64
 12  job_entrepreneur     4521 non-null   int64
 13  job_housemaid        4521 non-null   int64
 14  job_management       4521 non-null   int64
 15  job_retired          4521 non-null   int64
 16  job_self-employed    4521 non-null   int64
 17  job_services         4521 non-null   int64
 18  job_student          4521 non-null   int64
 19  job_technician       4521 non-null   int64
 20  job_unemployed       4521 non-null   int64
 21  job_unknown          4521 non-null   int64
 22  marital_married      4521 non-null   int64
 23  marital_single       4521 non-null   int64
 24  education_secondary  4521 non-null   int64
 25  education_tertiary   4521 non-null   int64
 26  education_unknown    4521 non-null   int64
 27  contact_telephone    4521 non-null   int64
 28  contact_unknown      4521 non-null   int64
 29  month_aug            4521 non-null   int64
 30  month_dec            4521 non-null   int64
 31  month_feb            4521 non-null   int64
 32  month_jan            4521 non-null   int64
 33  month_jul            4521 non-null   int64
 34  month_jun            4521 non-null   int64
 35  month_mar            4521 non-null   int64
 36  month_may            4521 non-null   int64
 37  month_nov            4521 non-null   int64
 38  month_oct            4521 non-null   int64
 39  month_sep            4521 non-null   int64
 40  poutcome_other       4521 non-null   int64
 41  poutcome_success     4521 non-null   int64
 42  poutcome_unknown     4521 non-null   int64
dtypes: int64(43)
memory usage: 1.5 MB

## **Feature Selection**
## **Selecting best features**

In [14]:
poutcome=['poutcome_unknown']
contact=['contact_unknown']
X=data.drop(columns=['y']+ poutcome + contact)
y=data['y']

# **Splitng the dataset for traing and testign**

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

## **Scaling Features**

In [17]:
Scaler=StandardScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.fit_transform(X_test)

## **Hyperparameter tuning**

In [18]:
param_grid = {
    'n_neighbors': range(3, 21),  # Test different values of k
    'weights': ['uniform', 'distance'],  # Weighting strategy
    'metric': ['euclidean', 'manhattan']  # Distance metric
}

## **Model Selection And Traing**

In [19]:
knn=KNeighborsClassifier()
grid_search=GridSearchCV(knn,param_grid,cv=5,scoring='accuracy')
grid_search.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': range(3, 21),
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

## **Predicting Y**

In [21]:
y_pred=grid_search.predict(X_test_scaled)

#Output where the customer will subscribe or not

In [22]:
for i, prediction in enumerate(y_pred):
  print(f"Customer {i+1} will {'subscribe' if prediction == 1 else 'not subscribe' } to the subscription ")

Customer 1 will not subscribe to the subscription
Customer 2 will not subscribe to the subscription
Customer 3 will not subscribe to the subscription
Customer 4 will not subscribe to the subscription
Customer 5 will not subscribe to the subscription
Customer 6 will not subscribe to the subscription
Customer 7 will not subscribe to the subscription
Customer 8 will not subscribe to the subscription
Customer 9 will not subscribe to the subscription
Customer 10 will not subscribe to the subscription
Customer 11 will not subscribe to the subscription
Customer 12 will not subscribe to the subscription
Customer 13 will not subscribe to the subscription
Customer 14 will not subscribe to the subscription
Customer 15 will not subscribe to the subscription
Customer 16 will not subscribe to the subscription
Customer 17 will not subscribe to the subscription
Customer 18 will not subscribe to the subscription
Customer 19 will not subscribe to the subscription
Customer 20 will not subscribe to the subscription
Customer 21 will not subscribe to the subscription
Customer 22 will not subscribe to the subscription
Customer 23 will subscribe to the subscription
Customer 24 will not subscribe to the subscription
Customer 25 will not subscribe to the subscription
Customer 26 will not subscribe to the subscription
Customer 27 will not subscribe to the subscription
Customer 28 will not subscribe to the subscription
Customer 29 will not subscribe to the subscription
Customer 30 will not subscribe to the subscription
Customer 31 will not subscribe to the subscription
Customer 32 will not subscribe to the subscription
Customer 33 will not subscribe to the subscription
Customer 34 will not subscribe to the subscription
Customer 35 will not subscribe to the subscription
Customer 36 will not subscribe to the subscription
Customer 37 will not subscribe to the subscription
Customer 38 will not subscribe to the subscription
Customer 39 will not subscribe to the subscription
Customer 40 will not subscribe to the subscription
Customer 41 will not subscribe to the subscription
Customer 42 will not subscribe to the subscription
Customer 43 will subscribe to the subscription
Customer 44 will not subscribe to the subscription
Customer 45 will not subscribe to the subscription
Customer 46 will not subscribe to the subscription
Customer 47 will not subscribe to the subscription
Customer 48 will not subscribe to the subscription
Customer 49 will not subscribe to the subscription
Customer 50 will not subscribe to the subscription
Customer 51 will not subscribe to the subscription
Customer 52 will not subscribe to the subscription
Customer 53 will not subscribe to the subscription
Customer 54 will not subscribe to the subscription
Customer 55 will not subscribe to the subscription
Customer 56 will not subscribe to the subscription
Customer 57 will not subscribe to the subscription
Customer 58 will not subscribe to the subscription
Customer 59 will not subscribe to the subscription
Customer 60 will not subscribe to the subscription
Customer 61 will not subscribe to the subscription
Customer 62 will not subscribe to the subscription
Customer 63 will not subscribe to the subscription
Customer 64 will not subscribe to the subscription
Customer 65 will not subscribe to the subscription
Customer 66 will not subscribe to the subscription
Customer 67 will not subscribe to the subscription
Customer 68 will not subscribe to the subscription
Customer 69 will not subscribe to the subscription
Customer 70 will not subscribe to the subscription
Customer 71 will not subscribe to the subscription
Customer 72 will not subscribe to the subscription
Customer 73 will not subscribe to the subscription
Customer 74 will not subscribe to the subscription
Customer 75 will not subscribe to the subscription
Customer 76 will not subscribe to the subscription
Customer 77 will not subscribe to the subscription
Customer 78 will not subscribe to the subscription
Customer 79 will not subscribe to the subscription
Customer 80 will not subscribe to the subscription
Customer 81 will not subscribe to the subscription
Customer 82 will not subscribe to the subscription
Customer 83 will not subscribe to the subscription
Customer 84 will not subscribe to the subscription
Customer 85 will not subscribe to the subscription
Customer 86 will not subscribe to the subscription
Customer 87 will not subscribe to the subscription
Customer 88 will not subscribe to the subscription
Customer 89 will subscribe to the subscription
Customer 90 will not subscribe to the subscription
Customer 91 will not subscribe to the subscription
Customer 92 will subscribe to the subscription
Customer 93 will not subscribe to the subscription
Customer 94 will not subscribe to the subscription
Customer 95 will not subscribe to the subscription
Customer 96 will not subscribe to the subscription
Customer 97 will not subscribe to the subscription
Customer 98 will not subscribe to the subscription
Customer 99 will not subscribe to the subscription
Customer 100 will not subscribe to the subscription
Customer 101 will not subscribe to the subscription
Customer 102 will not subscribe to the subscription
Customer 103 will not subscribe to the subscription
Customer 104 will not subscribe to the subscription
Customer 105 will not subscribe to the subscription
Customer 106 will not subscribe to the subscription
Customer 107 will not subscribe to the subscription
Customer 108 will not subscribe to the subscription
Customer 109 will not subscribe to the subscription
Customer 110 will not subscribe to the subscription
Customer 111 will not subscribe to the subscription
Customer 112 will not subscribe to the subscription
Customer 113 will not subscribe to the subscription
Customer 114 will not subscribe to the subscription
Customer 115 will not subscribe to the subscription
Customer 116 will not subscribe to the subscription
Customer 117 will not subscribe to the subscription
Customer 118 will not subscribe to the subscription
Customer 119 will not subscribe to the subscription
Customer 120 will not subscribe to the subscription
Customer 121 will not subscribe to the subscription
Customer 122 will not subscribe to the subscription
Customer 123 will not subscribe to the subscription
Customer 124 will not subscribe to the subscription
Customer 125 will not subscribe to the subscription
Customer 126 will not subscribe to the subscription
Customer 127 will not subscribe to the subscription
Customer 128 will not subscribe to the subscription
Customer 129 will not subscribe to the subscription
Customer 130 will not subscribe to the subscription
Customer 131 will not subscribe to the subscription
Customer 132 will not subscribe to the subscription
Customer 133 will not subscribe to the subscription
Customer 134 will not subscribe to the subscription
Customer 135 will not subscribe to the subscription
Customer 136 will not subscribe to the subscription
Customer 137 will not subscribe to the subscription
Customer 138 will not subscribe to the subscription
Customer 139 will not subscribe to the subscription
Customer 140 will not subscribe to the subscription
Customer 141 will not subscribe to the subscription
Customer 142 will not subscribe to the subscription
Customer 143 will not subscribe to the subscription
Customer 144 will not subscribe to the subscription
Customer 145 will not subscribe to the subscription
Customer 146 will not subscribe to the subscription
Customer 147 will not subscribe to the subscription
Customer 148 will not subscribe to the subscription
Customer 149 will not subscribe to the subscription
Customer 150 will not subscribe to the subscription
Customer 151 will not subscribe to the subscription
Customer 152 will not subscribe to the subscription
Customer 153 will not subscribe to the subscription
Customer 154 will not subscribe to the subscription
Customer 155 will not subscribe to the subscription
Customer 156 will not subscribe to the subscription
Customer 157 will not subscribe to the subscription
Customer 158 will not subscribe to the subscription
Customer 159 will not subscribe to the subscription
Customer 160 will not subscribe to the subscription
Customer 161 will not subscribe to the subscription
Customer 162 will not subscribe to the subscription
Customer 163 will not subscribe to the subscription
Customer 164 will not subscribe to the subscription
Customer 165 will not subscribe to the subscription
Customer 166 will not subscribe to the subscription
Customer 167 will not subscribe to the subscription
Customer 168 will not subscribe to the subscription
Customer 169 will not subscribe to the subscription
Customer 170 will subscribe to the subscription
Customer 171 will not subscribe to the subscription
Customer 172 will not subscribe to the subscription
Customer 173 will not subscribe to the subscription
Customer 174 will not subscribe to the subscription
Customer 175 will not subscribe to the subscription
Customer 176 will not subscribe to the subscription
Customer 177 will not subscribe to the subscription
Customer 178 will not subscribe to the subscription
Customer 179 will not subscribe to the subscription
Customer 180 will not subscribe to the subscription
Customer 181 will not subscribe to the subscription
Customer 182 will not subscribe to the subscription
Customer 183 will not subscribe to the subscription
Customer 184 will not subscribe to the subscription
Customer 185 will not subscribe to the subscription
Customer 186 will not subscribe to the subscription
Customer 187 will not subscribe to the subscription
Customer 188 will subscribe to the subscription
Customer 189 will not subscribe to the subscription
Customer 190 will not subscribe to the subscription
Customer 191 will not subscribe to the subscription
Customer 192 will not subscribe to the subscription
Customer 193 will not subscribe to the subscription
Customer 194 will not subscribe to the subscription
Customer 195 will not subscribe to the subscription
Customer 196 will not subscribe to the subscription
Customer 197 will not subscribe to the subscription
Customer 198 will not subscribe to the subscription
Customer 199 will not subscribe to the subscription
Customer 200 will not subscribe to the subscription
Customer 201 will not subscribe to the subscription
Customer 202 will not subscribe to the subscription
Customer 203 will subscribe to the subscription
Customer 204 will not subscribe to the subscription
Customer 205 will not subscribe to the subscription
Customer 206 will not subscribe to the subscription
Customer 207 will subscribe to the subscription
Customer 208 will not subscribe to the subscription
Customer 209 will not subscribe to the subscription
Customer 210 will not subscribe to the subscription
Customer 211 will not subscribe to the subscription
Customer 212 will not subscribe to the subscription
Customer 213 will not subscribe to the subscription
Customer 214 will not subscribe to the subscription
Customer 215 will not subscribe to the subscription
Customer 216 will not subscribe to the subscription
Customer 217 will not subscribe to the subscription
Customer 218 will not subscribe to the subscription
Customer 219 will not subscribe to the subscription
Customer 220 will not subscribe to the subscription
Customer 221 will not subscribe to the subscription
Customer 222 will not subscribe to the subscription
Customer 223 will not subscribe to the subscription
Customer 224 will not subscribe to the subscription
Customer 225 will not subscribe to the subscription
Customer 226 will not subscribe to the subscription
Customer 227 will not subscribe to the subscription
Customer 228 will not subscribe to the subscription
Customer 229 will not subscribe to the subscription
Customer 230 will not subscribe to the subscription
Customer 231 will not subscribe to the subscription
Customer 232 will not subscribe to the subscription
Customer 233 will not subscribe to the subscription
Customer 234 will not subscribe to the subscription
Customer 235 will not subscribe to the subscription
Customer 236 will not subscribe to the subscription
Customer 237 will not subscribe to the subscription
Customer 238 will not subscribe to the subscription
Customer 239 will not subscribe to the subscription
Customer 240 will not subscribe to the subscription
Customer 241 will not subscribe to the subscription
Customer 242 will not subscribe to the subscription
Customer 243 will not subscribe to the subscription
Customer 244 will not subscribe to the subscription
Customer 245 will not subscribe to the subscription
Customer 246 will not subscribe to the subscription
Customer 247 will not subscribe to the subscription
Customer 248 will not subscribe to the subscription
Customer 249 will not subscribe to the subscription
Customer 250 will not subscribe to the subscription
Customer 251 will not subscribe to the subscription
Customer 252 will not subscribe to the subscription
Customer 253 will not subscribe to the subscription
Customer 254 will not subscribe to the subscription
Customer 255 will not subscribe to the subscription
Customer 256 will not subscribe to the subscription
Customer 257 will not subscribe to the subscription
Customer 258 will not subscribe to the subscription
Customer 259 will not subscribe to the subscription
Customer 260 will not subscribe to the subscription
Customer 261 will subscribe to the subscription
Customer 262 will not subscribe to the subscription
Customer 263 will not subscribe to the subscription
Customer 264 will not subscribe to the subscription
Customer 265 will not subscribe to the subscription
Customer 266 will not subscribe to the subscription
Customer 267 will not subscribe to the subscription
Customer 268 will not subscribe to the subscription
Customer 269 will not subscribe to the subscription
Customer 270 will not subscribe to the subscription
Customer 271 will not subscribe to the subscription
Customer 272 will not subscribe to the subscription
Customer 273 will not subscribe to the subscription
Customer 274 will not subscribe to the subscription
Customer 275 will not subscribe to the subscription
Customer 276 will not subscribe to the subscription
Customer 277 will not subscribe to the subscription
Customer 278 will not subscribe to the subscription
Customer 279 will not subscribe to the subscription
Customer 280 will not subscribe to the subscription
Customer 281 will not subscribe to the subscription
Customer 282 will not subscribe to the subscription
Customer 283 will not subscribe to the subscription
Customer 284 will not subscribe to the subscription
Customer 285 will not subscribe to the subscription
Customer 286 will not subscribe to the subscription
Customer 287 will not subscribe to the subscription
Customer 288 will not subscribe to the subscription
Customer 289 will not subscribe to the subscription
Customer 290 will not subscribe to the subscription
Customer 291 will not subscribe to the subscription
Customer 292 will not subscribe to the subscription
Customer 293 will not subscribe to the subscription
Customer 294 will not subscribe to the subscription
Customer 295 will not subscribe to the subscription
Customer 296 will not subscribe to the subscription
Customer 297 will not subscribe to the subscription
Customer 298 will not subscribe to the subscription
Customer 299 will not subscribe to the subscription
Customer 300 will not subscribe to the subscription
Customer 301 will subscribe to the subscription
Customer 302 will subscribe to the subscription
Customer 303 will not subscribe to the subscription
Customer 304 will not subscribe to the subscription
Customer 305 will not subscribe to the subscription
Customer 306 will not subscribe to the subscription
Customer 307 will not subscribe to the subscription
Customer 308 will not subscribe to the subscription
Customer 309 will not subscribe to the subscription
Customer 310 will not subscribe to the subscription
Customer 311 will not subscribe to the subscription
Customer 312 will not subscribe to the subscription
Customer 313 will not subscribe to the subscription
Customer 314 will not subscribe to the subscription
Customer 315 will not subscribe to the subscription
Customer 316 will not subscribe to the subscription
Customer 317 will not subscribe to the subscription
Customer 318 will not subscribe to the subscription
Customer 319 will not subscribe to the subscription
Customer 320 will not subscribe to the subscription
Customer 321 will not subscribe to the subscription
Customer 322 will not subscribe to the subscription
Customer 323 will not subscribe to the subscription
Customer 324 will not subscribe to the subscription
Customer 325 will not subscribe to the subscription
Customer 326 will not subscribe to the subscription
Customer 327 will not subscribe to the subscription
Customer 328 will not subscribe to the subscription
Customer 329 will not subscribe to the subscription
Customer 330 will not subscribe to the subscription
Customer 331 will not subscribe to the subscription
Customer 332 will not subscribe to the subscription
Customer 333 will not subscribe to the subscription
Customer 334 will not subscribe to the subscription
Customer 335 will not subscribe to the subscription
Customer 336 will not subscribe to the subscription
Customer 337 will not subscribe to the subscription
Customer 338 will not subscribe to the subscription
Customer 339 will not subscribe to the subscription
Customer 340 will not subscribe to the subscription
Customer 341 will not subscribe to the subscription
Customer 342 will not subscribe to the subscription
Customer 343 will not subscribe to the subscription
Customer 344 will not subscribe to the subscription
Customer 345 will not subscribe to the subscription
Customer 346 will not subscribe to the subscription
Customer 347 will not subscribe to the subscription
Customer 348 will not subscribe to the subscription
Customer 349 will not subscribe to the subscription
Customer 350 will not subscribe to the subscription
Customer 351 will not subscribe to the subscription
Customer 352 will not subscribe to the subscription
Customer 353 will not subscribe to the subscription
Customer 354 will not subscribe to the subscription
Customer 355 will not subscribe to the subscription
Customer 356 will subscribe to the subscription
Customer 357 will not subscribe to the subscription
Customer 358 will not subscribe to the subscription
Customer 359 will not subscribe to the subscription
Customer 360 will not subscribe to the subscription
Customer 361 will not subscribe to the subscription
Customer 362 will not subscribe to the subscription
Customer 363 will not subscribe to the subscription
Customer 364 will not subscribe to the subscription
Customer 365 will not subscribe to the subscription
Customer 366 will not subscribe to the subscription
Customer 367 will not subscribe to the subscription
Customer 368 will not subscribe to the subscription
Customer 369 will not subscribe to the subscription
Customer 370 will subscribe to the subscription
Customer 371 will not subscribe to the subscription
Customer 372 will not subscribe to the subscription
Customer 373 will not subscribe to the subscription
Customer 374 will not subscribe to the subscription
Customer 375 will not subscribe to the subscription
Customer 376 will not subscribe to the subscription
Customer 377 will not subscribe to the subscription
Customer 378 will not subscribe to the subscription
Customer 379 will not subscribe to the subscription
Customer 380 will not subscribe to the subscription
Customer 381 will not subscribe to the subscription
Customer 382 will not subscribe to the subscription
Customer 383 will not subscribe to the subscription
Customer 384 will not subscribe to the subscription
Customer 385 will not subscribe to the subscription
Customer 386 will not subscribe to the subscription
Customer 387 will not subscribe to the subscription

## **Count No. of Employee able or unable to subscribe**

In [23]:
count_able = 0
count_unable=0

for prediction in y_pred:
  if prediction ==1 :
    count_able +=1
  else:
    count_unable +=1

print(f'No. of customer able to subscribe {count_able}')

print(f'No. of customer able to subscribe {count_unable}')

No. of customer able to subscribe 30
No. of customer able to subscribe 875

## **Evaluating Model**

In [24]:
#accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.89

In [25]:
# Detailed classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.98      0.94       807
           1       0.40      0.12      0.19        98

    accuracy                           0.89       905
   macro avg       0.65      0.55      0.56       905
weighted avg       0.85      0.89      0.86       905

In [26]:
# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[789  18]
 [ 86  12]]

## **Based on given users data like his work area, qualification, marrital status, predicted whether user will make more than 50k a year or not.**

## **Feature Selection**

In [41]:
# Define column names correctly (as lists of column names, not dataframes)
work_area_cols = ['job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management',
                  'job_retired', 'job_self-employed', 'job_services', 'job_student',
                  'job_technician', 'job_unemployed', 'job_unknown']

qualification_cols = ['education_secondary', 'education_tertiary', 'education_unknown']

marital_status_cols = ['marital_married', 'marital_single']

# Selecting relevant features from the dataframe
X = data[work_area_cols + qualification_cols + marital_status_cols]

# Target variable
y = data['y']

In [42]:
X.head()

,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,education_secondary,education_tertiary,education_unknown,marital_married,marital_single
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
2,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1
3,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0
4,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0

## **Spliting dataset**

In [43]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2 , random_state=42)

## **Standardizing the features using StandardScaler**

In [44]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## **Hyperparameter tuning for KNN using GridSearchCV**

In [45]:
param_grid = {'n_neighbors': np.arange(1, 30)}  # Testing k values from 1 to 30
knn = KNeighborsClassifier()
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])},
             scoring='accuracy')

## **Get the best K value**

In [46]:
best_k = grid_search.best_params_['n_neighbors']
print(f"Best K value: {best_k}")

Best K value: 12

## **Train the final KNN model with the best K**

In [47]:
knn_final = KNeighborsClassifier(n_neighbors=best_k)
knn_final.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=12)

## **Predictions**

In [48]:
y_pred = knn_final.predict(X_test_scaled)

## **Prediction output for each customer who is able to earn >50k based on job, qualification and marital status**

In [49]:
for i, prediction in enumerate(y_pred):
    print(f'Customer {i+1} will {"be able" if prediction == 1 else "not be able"} to make more than 50k a year.')

Customer 1 will not be able to make more than 50k a year.
Customer 2 will not be able to make more than 50k a year.
Customer 3 will not be able to make more than 50k a year.
Customer 4 will not be able to make more than 50k a year.
Customer 5 will not be able to make more than 50k a year.
Customer 6 will not be able to make more than 50k a year.
Customer 7 will not be able to make more than 50k a year.
Customer 8 will not be able to make more than 50k a year.
Customer 9 will not be able to make more than 50k a year.
Customer 10 will not be able to make more than 50k a year.
Customer 11 will not be able to make more than 50k a year.
Customer 12 will not be able to make more than 50k a year.
Customer 13 will not be able to make more than 50k a year.
Customer 14 will not be able to make more than 50k a year.
Customer 15 will not be able to make more than 50k a year.
Customer 16 will not be able to make more than 50k a year.
Customer 17 will not be able to make more than 50k a year.
Customer 18 will not be able to make more than 50k a year.
Customer 19 will not be able to make more than 50k a year.
Customer 20 will not be able to make more than 50k a year.
Customer 21 will not be able to make more than 50k a year.
Customer 22 will not be able to make more than 50k a year.
Customer 23 will not be able to make more than 50k a year.
Customer 24 will not be able to make more than 50k a year.
Customer 25 will not be able to make more than 50k a year.
Customer 26 will not be able to make more than 50k a year.
Customer 27 will not be able to make more than 50k a year.
Customer 28 will not be able to make more than 50k a year.
Customer 29 will not be able to make more than 50k a year.
Customer 30 will not be able to make more than 50k a year.
Customer 31 will not be able to make more than 50k a year.
Customer 32 will not be able to make more than 50k a year.
Customer 33 will not be able to make more than 50k a year.
Customer 34 will not be able to make more than 50k a year.
Customer 35 will not be able to make more than 50k a year.
Customer 36 will not be able to make more than 50k a year.
Customer 37 will not be able to make more than 50k a year.
Customer 38 will not be able to make more than 50k a year.
Customer 39 will not be able to make more than 50k a year.
Customer 40 will not be able to make more than 50k a year.
Customer 41 will not be able to make more than 50k a year.
Customer 42 will not be able to make more than 50k a year.
Customer 43 will not be able to make more than 50k a year.
Customer 44 will not be able to make more than 50k a year.
Customer 45 will not be able to make more than 50k a year.
Customer 46 will not be able to make more than 50k a year.
Customer 47 will not be able to make more than 50k a year.
Customer 48 will not be able to make more than 50k a year.
Customer 49 will not be able to make more than 50k a year.
Customer 50 will not be able to make more than 50k a year.
Customer 51 will not be able to make more than 50k a year.
Customer 52 will not be able to make more than 50k a year.
Customer 53 will not be able to make more than 50k a year.
Customer 54 will not be able to make more than 50k a year.
Customer 55 will not be able to make more than 50k a year.
Customer 56 will not be able to make more than 50k a year.
Customer 57 will not be able to make more than 50k a year.
Customer 58 will not be able to make more than 50k a year.
Customer 59 will not be able to make more than 50k a year.
Customer 60 will not be able to make more than 50k a year.
Customer 61 will not be able to make more than 50k a year.
Customer 62 will not be able to make more than 50k a year.
Customer 63 will not be able to make more than 50k a year.
Customer 64 will not be able to make more than 50k a year.
Customer 65 will not be able to make more than 50k a year.
Customer 66 will not be able to make more than 50k a year.
Customer 67 will not be able to make more than 50k a year.
Customer 68 will not be able to make more than 50k a year.
Customer 69 will not be able to make more than 50k a year.
Customer 70 will not be able to make more than 50k a year.
Customer 71 will not be able to make more than 50k a year.
Customer 72 will not be able to make more than 50k a year.
Customer 73 will not be able to make more than 50k a year.
Customer 74 will not be able to make more than 50k a year.
Customer 75 will not be able to make more than 50k a year.
Customer 76 will not be able to make more than 50k a year.
Customer 77 will not be able to make more than 50k a year.
Customer 78 will not be able to make more than 50k a year.
Customer 79 will not be able to make more than 50k a year.
Customer 80 will not be able to make more than 50k a year.
Customer 81 will not be able to make more than 50k a year.
Customer 82 will not be able to make more than 50k a year.
Customer 83 will not be able to make more than 50k a year.
Customer 84 will not be able to make more than 50k a year.
Customer 85 will not be able to make more than 50k a year.
Customer 86 will not be able to make more than 50k a year.
Customer 87 will not be able to make more than 50k a year.
Customer 88 will not be able to make more than 50k a year.
Customer 89 will not be able to make more than 50k a year.
Customer 90 will not be able to make more than 50k a year.
Customer 91 will not be able to make more than 50k a year.
Customer 92 will not be able to make more than 50k a year.
Customer 93 will not be able to make more than 50k a year.
Customer 94 will not be able to make more than 50k a year.
Customer 95 will not be able to make more than 50k a year.
Customer 96 will not be able to make more than 50k a year.
Customer 97 will not be able to make more than 50k a year.
Customer 98 will not be able to make more than 50k a year.
Customer 99 will not be able to make more than 50k a year.
Customer 100 will not be able to make more than 50k a year.
Customer 101 will not be able to make more than 50k a year.
Customer 102 will not be able to make more than 50k a year.
Customer 103 will not be able to make more than 50k a year.
Customer 104 will not be able to make more than 50k a year.
Customer 105 will not be able to make more than 50k a year.
Customer 106 will not be able to make more than 50k a year.
Customer 107 will not be able to make more than 50k a year.
Customer 108 will not be able to make more than 50k a year.
Customer 109 will not be able to make more than 50k a year.
Customer 110 will not be able to make more than 50k a year.
Customer 111 will not be able to make more than 50k a year.
Customer 112 will not be able to make more than 50k a year.
Customer 113 will not be able to make more than 50k a year.
Customer 114 will not be able to make more than 50k a year.
Customer 115 will not be able to make more than 50k a year.
Customer 116 will not be able to make more than 50k a year.
Customer 117 will not be able to make more than 50k a year.
Customer 118 will not be able to make more than 50k a year.
Customer 119 will not be able to make more than 50k a year.
Customer 120 will not be able to make more than 50k a year.
Customer 121 will not be able to make more than 50k a year.
Customer 122 will not be able to make more than 50k a year.
Customer 123 will not be able to make more than 50k a year.
Customer 124 will not be able to make more than 50k a year.
Customer 125 will not be able to make more than 50k a year.
Customer 126 will not be able to make more than 50k a year.
Customer 127 will not be able to make more than 50k a year.
Customer 128 will not be able to make more than 50k a year.
Customer 129 will not be able to make more than 50k a year.
Customer 130 will not be able to make more than 50k a year.
Customer 131 will not be able to make more than 50k a year.
Customer 132 will not be able to make more than 50k a year.
Customer 133 will not be able to make more than 50k a year.
Customer 134 will not be able to make more than 50k a year.
Customer 135 will not be able to make more than 50k a year.
Customer 136 will not be able to make more than 50k a year.
Customer 137 will not be able to make more than 50k a year.
Customer 138 will not be able to make more than 50k a year.
Customer 139 will not be able to make more than 50k a year.
Customer 140 will not be able to make more than 50k a year.
Customer 141 will not be able to make more than 50k a year.
Customer 142 will not be able to make more than 50k a year.
Customer 143 will not be able to make more than 50k a year.
Customer 144 will not be able to make more than 50k a year.
Customer 145 will not be able to make more than 50k a year.
Customer 146 will not be able to make more than 50k a year.
Customer 147 will not be able to make more than 50k a year.
Customer 148 will not be able to make more than 50k a year.
Customer 149 will not be able to make more than 50k a year.
Customer 150 will not be able to make more than 50k a year.
Customer 151 will not be able to make more than 50k a year.
Customer 152 will not be able to make more than 50k a year.
Customer 153 will not be able to make more than 50k a year.
Customer 154 will not be able to make more than 50k a year.
Customer 155 will not be able to make more than 50k a year.
Customer 156 will not be able to make more than 50k a year.
Customer 157 will not be able to make more than 50k a year.
Customer 158 will not be able to make more than 50k a year.
Customer 159 will not be able to make more than 50k a year.
Customer 160 will not be able to make more than 50k a year.
Customer 161 will not be able to make more than 50k a year.
Customer 162 will not be able to make more than 50k a year.
Customer 163 will not be able to make more than 50k a year.
Customer 164 will not be able to make more than 50k a year.
Customer 165 will not be able to make more than 50k a year.
Customer 166 will not be able to make more than 50k a year.
Customer 167 will not be able to make more than 50k a year.
Customer 168 will not be able to make more than 50k a year.
Customer 169 will not be able to make more than 50k a year.
Customer 170 will not be able to make more than 50k a year.
Customer 171 will not be able to make more than 50k a year.
Customer 172 will not be able to make more than 50k a year.
Customer 173 will not be able to make more than 50k a year.
Customer 174 will not be able to make more than 50k a year.
Customer 175 will not be able to make more than 50k a year.
Customer 176 will not be able to make more than 50k a year.
Customer 177 will not be able to make more than 50k a year.
Customer 178 will not be able to make more than 50k a year.
Customer 179 will not be able to make more than 50k a year.
Customer 180 will not be able to make more than 50k a year.
Customer 181 will not be able to make more than 50k a year.
Customer 182 will not be able to make more than 50k a year.
Customer 183 will not be able to make more than 50k a year.
Customer 184 will not be able to make more than 50k a year.
Customer 185 will not be able to make more than 50k a year.
Customer 186 will not be able to make more than 50k a year.
Customer 187 will not be able to make more than 50k a year.
Customer 188 will not be able to make more than 50k a year.
Customer 189 will not be able to make more than 50k a year.
Customer 190 will not be able to make more than 50k a year.
Customer 191 will not be able to make more than 50k a year.
Customer 192 will not be able to make more than 50k a year.
Customer 193 will not be able to make more than 50k a year.
Customer 194 will not be able to make more than 50k a year.
Customer 195 will not be able to make more than 50k a year.
Customer 196 will not be able to make more than 50k a year.
Customer 197 will not be able to make more than 50k a year.
Customer 198 will not be able to make more than 50k a year.
Customer 199 will not be able to make more than 50k a year.
Customer 200 will not be able to make more than 50k a year.
Customer 201 will not be able to make more than 50k a year.
Customer 202 will not be able to make more than 50k a year.
Customer 203 will not be able to make more than 50k a year.
Customer 204 will not be able to make more than 50k a year.
Customer 205 will not be able to make more than 50k a year.
Customer 206 will not be able to make more than 50k a year.
Customer 207 will not be able to make more than 50k a year.
Customer 208 will not be able to make more than 50k a year.
Customer 209 will not be able to make more than 50k a year.
Customer 210 will not be able to make more than 50k a year.
Customer 211 will not be able to make more than 50k a year.
Customer 212 will not be able to make more than 50k a year.
Customer 213 will not be able to make more than 50k a year.
Customer 214 will not be able to make more than 50k a year.
Customer 215 will not be able to make more than 50k a year.
Customer 216 will not be able to make more than 50k a year.
Customer 217 will not be able to make more than 50k a year.
Customer 218 will not be able to make more than 50k a year.
Customer 219 will not be able to make more than 50k a year.
Customer 220 will not be able to make more than 50k a year.
Customer 221 will not be able to make more than 50k a year.
Customer 222 will not be able to make more than 50k a year.
Customer 223 will not be able to make more than 50k a year.
Customer 224 will not be able to make more than 50k a year.
Customer 225 will not be able to make more than 50k a year.
Customer 226 will not be able to make more than 50k a year.
Customer 227 will not be able to make more than 50k a year.
Customer 228 will not be able to make more than 50k a year.
Customer 229 will not be able to make more than 50k a year.
Customer 230 will not be able to make more than 50k a year.
Customer 231 will not be able to make more than 50k a year.
Customer 232 will not be able to make more than 50k a year.
Customer 233 will not be able to make more than 50k a year.
Customer 234 will not be able to make more than 50k a year.
Customer 235 will not be able to make more than 50k a year.
Customer 236 will not be able to make more than 50k a year.
Customer 237 will not be able to make more than 50k a year.
Customer 238 will not be able to make more than 50k a year.
Customer 239 will not be able to make more than 50k a year.
Customer 240 will not be able to make more than 50k a year.
Customer 241 will not be able to make more than 50k a year.
Customer 242 will not be able to make more than 50k a year.
Customer 243 will not be able to make more than 50k a year.
Customer 244 will not be able to make more than 50k a year.
Customer 245 will not be able to make more than 50k a year.
Customer 246 will not be able to make more than 50k a year.
Customer 247 will not be able to make more than 50k a year.
Customer 248 will not be able to make more than 50k a year.
Customer 249 will not be able to make more than 50k a year.
Customer 250 will not be able to make more than 50k a year.
Customer 251 will not be able to make more than 50k a year.
Customer 252 will not be able to make more than 50k a year.
Customer 253 will not be able to make more than 50k a year.
Customer 254 will not be able to make more than 50k a year.
Customer 255 will not be able to make more than 50k a year.
Customer 256 will not be able to make more than 50k a year.
Customer 257 will not be able to make more than 50k a year.
Customer 258 will not be able to make more than 50k a year.
Customer 259 will not be able to make more than 50k a year.
Customer 260 will not be able to make more than 50k a year.
Customer 261 will not be able to make more than 50k a year.
Customer 262 will not be able to make more than 50k a year.
Customer 263 will not be able to make more than 50k a year.
Customer 264 will not be able to make more than 50k a year.
Customer 265 will not be able to make more than 50k a year.
Customer 266 will not be able to make more than 50k a year.
Customer 267 will not be able to make more than 50k a year.
Customer 268 will not be able to make more than 50k a year.
Customer 269 will not be able to make more than 50k a year.
Customer 270 will not be able to make more than 50k a year.
Customer 271 will not be able to make more than 50k a year.
Customer 272 will not be able to make more than 50k a year.
Customer 273 will not be able to make more than 50k a year.
Customer 274 will not be able to make more than 50k a year.
Customer 275 will not be able to make more than 50k a year.
Customer 276 will not be able to make more than 50k a year.
Customer 277 will not be able to make more than 50k a year.
Customer 278 will not be able to make more than 50k a year.
Customer 279 will not be able to make more than 50k a year.
Customer 280 will not be able to make more than 50k a year.
Customer 281 will not be able to make more than 50k a year.
Customer 282 will not be able to make more than 50k a year.
Customer 283 will not be able to make more than 50k a year.
Customer 284 will not be able to make more than 50k a year.
Customer 285 will not be able to make more than 50k a year.
Customer 286 will not be able to make more than 50k a year.
Customer 287 will not be able to make more than 50k a year.
Customer 288 will not be able to make more than 50k a year.
Customer 289 will not be able to make more than 50k a year.
Customer 290 will not be able to make more than 50k a year.
Customer 291 will not be able to make more than 50k a year.
Customer 292 will not be able to make more than 50k a year.
Customer 293 will not be able to make more than 50k a year.
Customer 294 will not be able to make more than 50k a year.
Customer 295 will not be able to make more than 50k a year.
Customer 296 will not be able to make more than 50k a year.
Customer 297 will not be able to make more than 50k a year.
Customer 298 will not be able to make more than 50k a year.
Customer 299 will not be able to make more than 50k a year.
Customer 300 will not be able to make more than 50k a year.
Customer 301 will not be able to make more than 50k a year.
Customer 302 will not be able to make more than 50k a year.
Customer 303 will not be able to make more than 50k a year.
Customer 304 will not be able to make more than 50k a year.
Customer 305 will not be able to make more than 50k a year.
Customer 306 will not be able to make more than 50k a year.
Customer 307 will not be able to make more than 50k a year.
Customer 308 will not be able to make more than 50k a year.
Customer 309 will not be able to make more than 50k a year.
Customer 310 will not be able to make more than 50k a year.
Customer 311 will not be able to make more than 50k a year.
Customer 312 will not be able to make more than 50k a year.
Customer 313 will not be able to make more than 50k a year.
Customer 314 will not be able to make more than 50k a year.
Customer 315 will not be able to make more than 50k a year.
Customer 316 will not be able to make more than 50k a year.
Customer 317 will not be able to make more than 50k a year.
Customer 318 will not be able to make more than 50k a year.
Customer 319 will not be able to make more than 50k a year.
Customer 320 will not be able to make more than 50k a year.
Customer 321 will not be able to make more than 50k a year.
Customer 322 will not be able to make more than 50k a year.
Customer 323 will not be able to make more than 50k a year.
Customer 324 will not be able to make more than 50k a year.
Customer 325 will not be able to make more than 50k a year.
Customer 326 will not be able to make more than 50k a year.
Customer 327 will not be able to make more than 50k a year.
Customer 328 will not be able to make more than 50k a year.
Customer 329 will not be able to make more than 50k a year.
Customer 330 will not be able to make more than 50k a year.
Customer 331 will not be able to make more than 50k a year.
Customer 332 will not be able to make more than 50k a year.
Customer 333 will not be able to make more than 50k a year.
Customer 334 will not be able to make more than 50k a year.
Customer 335 will not be able to make more than 50k a year.

## **Count No. of customer able or unable to subscribe**

In [50]:
count_able = 0
count_unable=0

for prediction in y_pred:
  if prediction ==1 :
    count_able +=1
  else:
    count_unable +=1

print(f'No. of customer able to subscribe {count_able}')

print(f'No. of customer able to subscribe {count_unable}')

No. of customer able to subscribe 0
No. of customer able to subscribe 905

## **Model Evaluation**

In [51]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8917

Classification Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94       807
           1       0.00      0.00      0.00        98

    accuracy                           0.89       905
   macro avg       0.45      0.50      0.47       905
weighted avg       0.80      0.89      0.84       905

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [52]:
# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[807   0]
 [ 98   0]]