## **Weather Problem**
# **Regression problems using multiple linear regression, predicted apparent temperature for given temperature, humidity, wind speed, visibility, pressure**

# **Loading the dataset**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# **Uploading the data from local to colab**

In [2]:
from google.colab import files
uploaded=files.upload()

Saving Weather_Data.csv to Weather_Data.csv

## **Reading CSV file data**

In [3]:
data=pd.read_csv('Weather_Data.csv')

## **Data Head**

In [4]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

## **Data Information**

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

# **Pre-Processing Code**

In [ ]:
# # Rename columns
# df.columns = ['Datetime', 'Temp [C]', 'Dew Point Temp [C]', 'Rel Hum [%]', 'Wind Speed [km/h]', 'Visibility [km]', 'Press [kPa]', 'Weather']

# # Convert time stamp column to time format
# df.index = pd.to_datetime(df['Datetime']).dt.floor('T')
# df = df.iloc[:, 1:]

# # Remove empty rows (if any are present in the data).
# df.drop(df[df.isnull().any(axis = 1)].index, inplace = True)

# # Remove duplicates (if any are present in the dataset).
# df.drop_duplicates(inplace = True)

# # Separate 'Weather' column into three separate parts (each description of weather conditions in a separate column)
# weather_split = ['Weather - p. 1', 'Weather - p. 2', 'Weather - p. 3']
# df[weather_split] = df['Weather'].str.split(',', expand = True)

# # Remove 'Weather' column (redundant).
# df.drop(['Weather'], axis = 1, inplace = True)

# # Storage of data on weather conditions according to zero-one coding.
# weather_category_list = np.array([])

# for column in df[weather_split]:
#     weather_category_list = np.append(weather_category_list, df[weather_split][column].unique())

# weather_category_list = weather_category_list[weather_category_list != None]
# weather_category_list = np.unique(weather_category_list)

# df[weather_category_list] = 0

# for column in df[weather_split]:
#     for index in df[weather_split].index:
#         if df.loc[index, column] != None:
#             df.at[index, df.loc[index, column]] = df.loc[index, df.loc[index, column]] + 1

# # Delete 'Weather - p. 1', 'Weather - p. 2' and 'Weather - p. 3' columns (redundant)
# df.drop(weather_split, axis = 1, inplace = True)

# # Create an auxiliary set of column names in measured values
# weather_measurement_data = ['Temp [C]', 'Dew Point Temp [C]', 'Rel Hum [%]', 'Wind Speed [km/h]', 'Visibility [km]', 'Press [kPa]']

## **Checking for null values in dataset**

In [8]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

## **Checking for redundant  data**

In [9]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8779    False
8780    False
8781    False
8782    False
8783    False
Length: 8784, dtype: bool

## **Data Pre-processing**

In [10]:
# Converting 'Date/Time' to datetime format and extracting useful information
data['Date/Time']=pd.to_datetime(data['Date/Time'])

data['Hour']=data['Date/Time'].dt.hour
data['Day']=data['Date/Time'].dt.day
data['Month']=data['Date/Time'].dt.month
data['weekday']=data['Date/Time'].dt.weekday

#now that we extracted  useful information from Date/Time column we can drop that column
X=data.drop(columns=['Date/Time'])

#converting weather column from categorical to numberical values using dummies
X = pd.get_dummies(X, columns=['Weather'], drop_first=True)

## **Dependent and Independent variable**

In [13]:
# Define the target variable (e.g., predicting 'Temp_C')
X_simple=data[['Dew Point Temp_C']]
y = data['Temp_C']

## **Spliting Dataset**

In [14]:
#Split Data (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X_simple, y, test_size=0.2, random_state=42)

## **Scaling numerical features**

In [15]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## **Ridge Regression Model**

In [19]:
ridge = Ridge()

# Hyperparameter Grid (alpha for Ridge)
param_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}

# Perform GridSearchCV to tune the hyperparameters
grid_search = GridSearchCV(estimator=ridge, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_squared_error')

## **Best Hyperparameters**

In [20]:
best_alpha = grid_search.best_params_['alpha']
best_score = grid_search.best_score_

## **Train the best model using the best alpha**

In [21]:
best_model = grid_search.best_estimator_
best_model.fit(X_train_scaled, y_train)

Ridge(alpha=0.1)

## **Predicting temperature**

In [22]:
y_pred=best_model.predict(X_test_scaled)

In [23]:
for i ,prediction in enumerate(y_pred):
  print(f"weather sample {i+1} predicted accumated temperature {prediction}")

weather sample 1 predicted accumated temperature 15.821422412730042
weather sample 2 predicted accumated temperature 3.001971064662449
weather sample 3 predicted accumated temperature 16.0217263400436
weather sample 4 predicted accumated temperature 7.809265320187797
weather sample 5 predicted accumated temperature -12.62173526579493
weather sample 6 predicted accumated temperature 23.533123614301957
weather sample 7 predicted accumated temperature -6.41231351907469
weather sample 8 predicted accumated temperature 16.722790085641044
weather sample 9 predicted accumated temperature 16.822942049297822
weather sample 10 predicted accumated temperature -14.424470611616934
weather sample 11 predicted accumated temperature 14.218990994221594
weather sample 12 predicted accumated temperature 21.63023630482317
weather sample 13 predicted accumated temperature 24.634795214526513
weather sample 14 predicted accumated temperature 1.4996916098107773
weather sample 15 predicted accumated temperature 17.32370186758171
weather sample 16 predicted accumated temperature 1.1992357188404439
weather sample 17 predicted accumated temperature 4.604402483170898
weather sample 18 predicted accumated temperature 5.205314265111567
weather sample 19 predicted accumated temperature 17.624157758552048
weather sample 20 predicted accumated temperature -4.609578173252684
weather sample 21 predicted accumated temperature 15.320662594446151
weather sample 22 predicted accumated temperature 2.3009073190650025
weather sample 23 predicted accumated temperature 13.017167430340255
weather sample 24 predicted accumated temperature 11.615039939145364
weather sample 25 predicted accumated temperature 2.901819101005671
weather sample 26 predicted accumated temperature 5.00501033779801
weather sample 27 predicted accumated temperature 4.904858374141233
weather sample 28 predicted accumated temperature 2.000451428094668
weather sample 29 predicted accumated temperature 5.706074083395457
weather sample 30 predicted accumated temperature 19.62719703168761
weather sample 31 predicted accumated temperature 22.932211832361283
weather sample 32 predicted accumated temperature -9.316720465121252
weather sample 33 predicted accumated temperature 5.00501033779801
weather sample 34 predicted accumated temperature 19.02628524974694
weather sample 35 predicted accumated temperature 6.807745683620016
weather sample 36 predicted accumated temperature 26.03692270572141
weather sample 37 predicted accumated temperature 9.411696738696246
weather sample 38 predicted accumated temperature 2.2007553554082246
weather sample 39 predicted accumated temperature 20.42841274094183
weather sample 40 predicted accumated temperature 5.906378010709014
weather sample 41 predicted accumated temperature -9.416872428778033
weather sample 42 predicted accumated temperature -4.80988210056624
weather sample 43 predicted accumated temperature -5.410793882506907
weather sample 44 predicted accumated temperature -0.0025878450408942655
weather sample 45 predicted accumated temperature 17.92461364952238
weather sample 46 predicted accumated temperature 26.93829037863241
weather sample 47 predicted accumated temperature -8.615656719523807
weather sample 48 predicted accumated temperature 8.510329065785243
weather sample 49 predicted accumated temperature 20.1279568499715
weather sample 50 predicted accumated temperature 12.215951721086032
weather sample 51 predicted accumated temperature 23.63327557795873
weather sample 52 predicted accumated temperature 3.803186773916674
weather sample 53 predicted accumated temperature 2.901819101005671
weather sample 54 predicted accumated temperature 13.317623321310592
weather sample 55 predicted accumated temperature 19.52704506803083
weather sample 56 predicted accumated temperature 2.7015151736921146
weather sample 57 predicted accumated temperature 24.434491287212957
weather sample 58 predicted accumated temperature 18.926133286090163
weather sample 59 predicted accumated temperature -14.124014720646601
weather sample 60 predicted accumated temperature 19.52704506803083
weather sample 61 predicted accumated temperature -1.2044114089222298
weather sample 62 predicted accumated temperature 23.63327557795873
weather sample 63 predicted accumated temperature 8.510329065785243
weather sample 64 predicted accumated temperature 1.6999955371243347
weather sample 65 predicted accumated temperature 4.303946592200564
weather sample 66 predicted accumated temperature 14.218990994221594
weather sample 67 predicted accumated temperature 22.63175594139095
weather sample 68 predicted accumated temperature 22.932211832361283
weather sample 69 predicted accumated temperature 1.4996916098107773
weather sample 70 predicted accumated temperature 22.932211832361283
weather sample 71 predicted accumated temperature 1.9002994644378894
weather sample 72 predicted accumated temperature -9.817480283405144
weather sample 73 predicted accumated temperature 0.49817197324299656
weather sample 74 predicted accumated temperature -2.0056271181764522
weather sample 75 predicted accumated temperature 25.335858960123964
weather sample 76 predicted accumated temperature 11.715191902802141
weather sample 77 predicted accumated temperature 16.322182231013933
weather sample 78 predicted accumated temperature 2.501211246378559
weather sample 79 predicted accumated temperature 13.317623321310592
weather sample 80 predicted accumated temperature -5.510945846163686
weather sample 81 predicted accumated temperature 23.43297165064518
weather sample 82 predicted accumated temperature 16.52248615832749
weather sample 83 predicted accumated temperature 3.302426955632784
weather sample 84 predicted accumated temperature 0.9989317915268865
weather sample 85 predicted accumated temperature 17.724309722208826
weather sample 86 predicted accumated temperature 11.715191902802141
weather sample 87 predicted accumated temperature -9.517024392434807
weather sample 88 predicted accumated temperature 24.2341873598994
weather sample 89 predicted accumated temperature 5.605922119738679
weather sample 90 predicted accumated temperature -11.720367592883926
weather sample 91 predicted accumated temperature 19.12643721340372
weather sample 92 predicted accumated temperature 10.21291244795047
weather sample 93 predicted accumated temperature 14.819902776162262
weather sample 94 predicted accumated temperature 20.027804886314723
weather sample 95 predicted accumated temperature 4.804706410484454
weather sample 96 predicted accumated temperature 24.33433932355618
weather sample 97 predicted accumated temperature 5.00501033779801
weather sample 98 predicted accumated temperature 25.1355550328104
weather sample 99 predicted accumated temperature 3.2022749919760054
weather sample 100 predicted accumated temperature 8.7106329930988
weather sample 101 predicted accumated temperature 1.099083755183667
weather sample 102 predicted accumated temperature -3.2074506820577913
weather sample 103 predicted accumated temperature 12.816863503026699
weather sample 104 predicted accumated temperature 6.206833901679348
weather sample 105 predicted accumated temperature 5.8062260470522356
weather sample 106 predicted accumated temperature 1.099083755183667
weather sample 107 predicted accumated temperature -18.029941303260948
weather sample 108 predicted accumated temperature 19.52704506803083
weather sample 109 predicted accumated temperature 10.613520302577584
weather sample 110 predicted accumated temperature 1.099083755183667
weather sample 111 predicted accumated temperature 22.73190790504773
weather sample 112 predicted accumated temperature 19.326741140717274
weather sample 113 predicted accumated temperature 19.226589177060497
weather sample 114 predicted accumated temperature 15.721270449073264
weather sample 115 predicted accumated temperature 21.830540232136727
weather sample 116 predicted accumated temperature 23.032363796018064
weather sample 117 predicted accumated temperature 15.92157437638682
weather sample 118 predicted accumated temperature 18.024765613179163
weather sample 119 predicted accumated temperature 16.42233419467071
weather sample 120 predicted accumated temperature 5.00501033779801
weather sample 121 predicted accumated temperature -16.62781381206605
weather sample 122 predicted accumated temperature 3.7030348102598962
weather sample 123 predicted accumated temperature 25.836618778407853
weather sample 124 predicted accumated temperature 24.033883432585846
weather sample 125 predicted accumated temperature 21.029324522882504
weather sample 126 predicted accumated temperature -1.0041074816086741
weather sample 127 predicted accumated temperature 19.92765292265794
weather sample 128 predicted accumated temperature 24.534643250869735
weather sample 129 predicted accumated temperature -4.309122282282351
weather sample 130 predicted accumated temperature -5.110337991536575
weather sample 131 predicted accumated temperature 1.6999955371243347
weather sample 132 predicted accumated temperature 21.429932377509616
weather sample 133 predicted accumated temperature 3.502730882946339
weather sample 134 predicted accumated temperature 3.1021230283192276
weather sample 135 predicted accumated temperature 27.33889823325952
weather sample 136 predicted accumated temperature 4.804706410484454
weather sample 137 predicted accumated temperature 5.105162301454788
weather sample 138 predicted accumated temperature 19.727348995344386
weather sample 139 predicted accumated temperature 4.1036426648870075
weather sample 140 predicted accumated temperature 19.12643721340372
weather sample 141 predicted accumated temperature 23.83357950527229
weather sample 142 predicted accumated temperature 15.02020670347582
weather sample 143 predicted accumated temperature 2.7015151736921146
weather sample 144 predicted accumated temperature 14.619598848848707
weather sample 145 predicted accumated temperature 20.929172559225727
weather sample 146 predicted accumated temperature 15.320662594446151
weather sample 147 predicted accumated temperature 1.2993876824972217
weather sample 148 predicted accumated temperature -7.013225301015359
weather sample 149 predicted accumated temperature 22.932211832361283
weather sample 150 predicted accumated temperature 13.618079212280925
weather sample 151 predicted accumated temperature 11.014128157204695
weather sample 152 predicted accumated temperature 20.829020595568945
weather sample 153 predicted accumated temperature 19.02628524974694
weather sample 154 predicted accumated temperature 2.7015151736921146
weather sample 155 predicted accumated temperature 17.724309722208826
weather sample 156 predicted accumated temperature 7.809265320187797
weather sample 157 predicted accumated temperature 5.00501033779801
weather sample 158 predicted accumated temperature -20.633892358337178
weather sample 159 predicted accumated temperature 8.810784956755578
weather sample 160 predicted accumated temperature -1.6050192635493428
weather sample 161 predicted accumated temperature 1.3995396461539995
weather sample 162 predicted accumated temperature 22.13099612310706
weather sample 163 predicted accumated temperature 16.0217263400436
weather sample 164 predicted accumated temperature 20.62871666825539
weather sample 165 predicted accumated temperature 2.7015151736921146
weather sample 166 predicted accumated temperature 23.533123614301957
weather sample 167 predicted accumated temperature 14.218990994221594
weather sample 168 predicted accumated temperature 8.61048102944202
weather sample 169 predicted accumated temperature 25.436010923780735
weather sample 170 predicted accumated temperature 0.39802000958621875
weather sample 171 predicted accumated temperature 16.722790085641044
weather sample 172 predicted accumated temperature 16.52248615832749
weather sample 173 predicted accumated temperature 18.024765613179163
weather sample 174 predicted accumated temperature 16.0217263400436
weather sample 175 predicted accumated temperature -4.108818354968795
weather sample 176 predicted accumated temperature 9.311544775039469
weather sample 177 predicted accumated temperature 25.1355550328104
weather sample 178 predicted accumated temperature -15.926750066468609
weather sample 179 predicted accumated temperature 19.226589177060497
weather sample 180 predicted accumated temperature -0.3030437360112259
weather sample 181 predicted accumated temperature 0.8987798278701087
weather sample 182 predicted accumated temperature 14.719750812505485
weather sample 183 predicted accumated temperature 16.42233419467071
weather sample 184 predicted accumated temperature 23.83357950527229
weather sample 185 predicted accumated temperature -3.407754609371345
weather sample 186 predicted accumated temperature 19.62719703168761
weather sample 187 predicted accumated temperature 9.511848702353024
weather sample 188 predicted accumated temperature -2.1057790818332336
weather sample 189 predicted accumated temperature 8.310025138471687
weather sample 190 predicted accumated temperature 19.326741140717274
weather sample 191 predicted accumated temperature -1.8053231908628984
weather sample 192 predicted accumated temperature -0.8038035542951167
weather sample 193 predicted accumated temperature 19.426893104374052
weather sample 194 predicted accumated temperature -1.104259445265452
weather sample 195 predicted accumated temperature 7.709113356531018
weather sample 196 predicted accumated temperature 10.012608520636913
weather sample 197 predicted accumated temperature -11.11945581094326
weather sample 198 predicted accumated temperature 8.310025138471687
weather sample 199 predicted accumated temperature -3.307602645714569
weather sample 200 predicted accumated temperature 23.83357950527229
weather sample 201 predicted accumated temperature 4.404098555857342
weather sample 202 predicted accumated temperature -7.1133772646721365
weather sample 203 predicted accumated temperature -15.726446139155046
weather sample 204 predicted accumated temperature 13.718231175937703
weather sample 205 predicted accumated temperature 19.727348995344386
weather sample 206 predicted accumated temperature -5.310641918850131
weather sample 207 predicted accumated temperature 15.92157437638682
weather sample 208 predicted accumated temperature 18.725829358776608
weather sample 209 predicted accumated temperature 10.81382422989114
weather sample 210 predicted accumated temperature -14.524622575273712
weather sample 211 predicted accumated temperature 18.525525431463052
weather sample 212 predicted accumated temperature 9.211392811382689
weather sample 213 predicted accumated temperature -0.7036515906383389
weather sample 214 predicted accumated temperature 15.220510630789374
weather sample 215 predicted accumated temperature 2.4010592827217803
weather sample 216 predicted accumated temperature -3.808362463998458
weather sample 217 predicted accumated temperature 5.605922119738679
weather sample 218 predicted accumated temperature 23.3328196869884
weather sample 219 predicted accumated temperature 19.426893104374052
weather sample 220 predicted accumated temperature -2.506386936460345
weather sample 221 predicted accumated temperature -11.019303847286482
weather sample 222 predicted accumated temperature 24.634795214526513
weather sample 223 predicted accumated temperature 21.129476486539282
weather sample 224 predicted accumated temperature 18.22506954049272
weather sample 225 predicted accumated temperature 2.601363210035336
weather sample 226 predicted accumated temperature 5.305466228768346
weather sample 227 predicted accumated temperature 21.429932377509616
weather sample 228 predicted accumated temperature 21.830540232136727
weather sample 229 predicted accumated temperature 8.410177102128465
weather sample 230 predicted accumated temperature 15.120358667132596
weather sample 231 predicted accumated temperature -1.7051712272061206
weather sample 232 predicted accumated temperature -17.42902952132028
weather sample 233 predicted accumated temperature 16.0217263400436
weather sample 234 predicted accumated temperature 11.21443208451825
weather sample 235 predicted accumated temperature 14.018687066908036
weather sample 236 predicted accumated temperature 23.63327557795873
weather sample 237 predicted accumated temperature 17.223549903924933
weather sample 238 predicted accumated temperature -0.3030437360112259
weather sample 239 predicted accumated temperature 6.7075937199632385
weather sample 240 predicted accumated temperature 6.7075937199632385
weather sample 241 predicted accumated temperature 10.613520302577584
weather sample 242 predicted accumated temperature 24.134035396242624
weather sample 243 predicted accumated temperature -15.926750066468609
weather sample 244 predicted accumated temperature 0.7986278642133318
weather sample 245 predicted accumated temperature 10.81382422989114
weather sample 246 predicted accumated temperature 22.932211832361283
weather sample 247 predicted accumated temperature 4.203794628543786
weather sample 248 predicted accumated temperature 15.120358667132596
weather sample 249 predicted accumated temperature 5.305466228768346
weather sample 250 predicted accumated temperature -17.22872559400672
weather sample 251 predicted accumated temperature 21.530084341166393
weather sample 252 predicted accumated temperature 23.13251575967484
weather sample 253 predicted accumated temperature 23.63327557795873
weather sample 254 predicted accumated temperature 16.121878303700377
weather sample 255 predicted accumated temperature -4.910034064223018
weather sample 256 predicted accumated temperature 5.906378010709014
weather sample 257 predicted accumated temperature 12.416255648399588
weather sample 258 predicted accumated temperature 23.533123614301957
weather sample 259 predicted accumated temperature 15.52096652175971
weather sample 260 predicted accumated temperature 20.42841274094183
weather sample 261 predicted accumated temperature -19.73252468542617
weather sample 262 predicted accumated temperature 21.930692195793505
weather sample 263 predicted accumated temperature 26.93829037863241
weather sample 264 predicted accumated temperature 22.83205986870451
weather sample 265 predicted accumated temperature 10.21291244795047
weather sample 266 predicted accumated temperature -16.828117739379614
weather sample 267 predicted accumated temperature 23.13251575967484
weather sample 268 predicted accumated temperature -4.609578173252684
weather sample 269 predicted accumated temperature 8.20987317481491
weather sample 270 predicted accumated temperature 0.29786804592944094
weather sample 271 predicted accumated temperature -12.221127411167815
weather sample 272 predicted accumated temperature 2.2007553554082246
weather sample 273 predicted accumated temperature 23.43297165064518
weather sample 274 predicted accumated temperature 8.310025138471687
weather sample 275 predicted accumated temperature -2.506386936460345
weather sample 276 predicted accumated temperature 19.12643721340372
weather sample 277 predicted accumated temperature 21.63023630482317
weather sample 278 predicted accumated temperature 15.02020670347582
weather sample 279 predicted accumated temperature 15.52096652175971
weather sample 280 predicted accumated temperature -5.410793882506907
weather sample 281 predicted accumated temperature 13.718231175937703
weather sample 282 predicted accumated temperature 26.03692270572141
weather sample 283 predicted accumated temperature 13.217471357653814
weather sample 284 predicted accumated temperature 25.335858960123964
weather sample 285 predicted accumated temperature 5.405618192425123
weather sample 286 predicted accumated temperature 22.431452014077394
weather sample 287 predicted accumated temperature 14.018687066908036
weather sample 288 predicted accumated temperature 2.601363210035336

## **Evaluate Model Performance**

In [24]:
# Calculate performance metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R² Score: {r2}")

Mean Squared Error (MSE): 18.631761787273646
R² Score: 0.8713486548457821

## **Multiple linear regression**

In [25]:
# Select multiple independent variables
y = data["Temp_C"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## **Scaling the features**

In [26]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## **Ridge Regression Model**

In [27]:
ridge = Ridge()

# Hyperparameter Grid (alpha for Ridge)
param_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}

# Perform GridSearchCV to tune the hyperparameters
grid_search = GridSearchCV(estimator=ridge, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_squared_error')

## **Best Hyperparameters**

In [28]:
best_alpha = grid_search.best_params_['alpha']
best_score = grid_search.best_score_

## **Train the best model using the best alpha**

In [29]:
best_model = grid_search.best_estimator_
best_model.fit(X_train_scaled, y_train)

Ridge(alpha=0.01)

## **Predicting the temp**

In [30]:
# Make predictions
y_pred=best_model.predict(X_test_scaled)

In [32]:
for i ,prediction in enumerate(y_pred):
  print(f"weather sample {i+1} predicted accumated temperature {prediction}")

weather sample 1 predicted accumated temperature 12.799941743409008
weather sample 2 predicted accumated temperature 1.000037217071208
weather sample 3 predicted accumated temperature 12.599917544411541
weather sample 4 predicted accumated temperature 11.700181800597758
weather sample 5 predicted accumated temperature -11.599677541383455
weather sample 6 predicted accumated temperature 21.100000674265097
weather sample 7 predicted accumated temperature -9.600028838547052
weather sample 8 predicted accumated temperature 19.600155744953337
weather sample 9 predicted accumated temperature 24.19972144098726
weather sample 10 predicted accumated temperature -15.199849977185513
weather sample 11 predicted accumated temperature 17.60021584566504
weather sample 12 predicted accumated temperature 22.60022378246648
weather sample 13 predicted accumated temperature 20.999940413954878
weather sample 14 predicted accumated temperature 3.0001805508369754
weather sample 15 predicted accumated temperature 14.800070251324218
weather sample 16 predicted accumated temperature -2.00017651060352
weather sample 17 predicted accumated temperature 4.800145009587312
weather sample 18 predicted accumated temperature 4.800172731522113
weather sample 19 predicted accumated temperature 16.500098631904194
weather sample 20 predicted accumated temperature 1.0003548415489218
weather sample 21 predicted accumated temperature 14.000021809631681
weather sample 22 predicted accumated temperature 2.6001112520382277
weather sample 23 predicted accumated temperature 22.39960258394897
weather sample 24 predicted accumated temperature 14.5001773056512
weather sample 25 predicted accumated temperature -1.1000036630223988
weather sample 26 predicted accumated temperature 0.6997880191419714
weather sample 27 predicted accumated temperature 4.400239127587702
weather sample 28 predicted accumated temperature 5.9002246189395215
weather sample 29 predicted accumated temperature 2.199868940722796
weather sample 30 predicted accumated temperature 15.699906369938432
weather sample 31 predicted accumated temperature 21.900244071015955
weather sample 32 predicted accumated temperature -8.599731715290668
weather sample 33 predicted accumated temperature 0.8000288138837082
weather sample 34 predicted accumated temperature 24.19998805291757
weather sample 35 predicted accumated temperature 12.300062185039742
weather sample 36 predicted accumated temperature 24.100056507702696
weather sample 37 predicted accumated temperature 8.800135232071858
weather sample 38 predicted accumated temperature 13.799247038820228
weather sample 39 predicted accumated temperature 21.10025206060537
weather sample 40 predicted accumated temperature 6.300198832368418
weather sample 41 predicted accumated temperature -8.599850485064612
weather sample 42 predicted accumated temperature -3.699687249399549
weather sample 43 predicted accumated temperature -6.600062515115791
weather sample 44 predicted accumated temperature -1.2998734361585704
weather sample 45 predicted accumated temperature 11.899453606865688
weather sample 46 predicted accumated temperature 28.900156652485478
weather sample 47 predicted accumated temperature -10.800049172019959
weather sample 48 predicted accumated temperature 11.900108871239821
weather sample 49 predicted accumated temperature 14.9997621844634
weather sample 50 predicted accumated temperature 10.100023411406523
weather sample 51 predicted accumated temperature 20.700077115033977
weather sample 52 predicted accumated temperature 1.1000384593237005
weather sample 53 predicted accumated temperature 3.9004332752577655
weather sample 54 predicted accumated temperature 10.19993662613854
weather sample 55 predicted accumated temperature 27.89966499234569
weather sample 56 predicted accumated temperature -0.2998936548642561
weather sample 57 predicted accumated temperature 24.500149492065134
weather sample 58 predicted accumated temperature 15.399916858717475
weather sample 59 predicted accumated temperature -12.599779496739858
weather sample 60 predicted accumated temperature 20.00024002353343
weather sample 61 predicted accumated temperature -6.300155910721372
weather sample 62 predicted accumated temperature 25.800147148594164
weather sample 63 predicted accumated temperature 4.39985859765264
weather sample 64 predicted accumated temperature -1.6003007767368018
weather sample 65 predicted accumated temperature -0.5005473427491545
weather sample 66 predicted accumated temperature 21.899797386953328
weather sample 67 predicted accumated temperature 26.600026589563583
weather sample 68 predicted accumated temperature 27.199957445060285
weather sample 69 predicted accumated temperature 0.8001285538422795
weather sample 70 predicted accumated temperature 17.19956425033759
weather sample 71 predicted accumated temperature 12.399414749522439
weather sample 72 predicted accumated temperature -11.90012273748488
weather sample 73 predicted accumated temperature -0.4998970172903068
weather sample 74 predicted accumated temperature -4.999948092332909
weather sample 75 predicted accumated temperature 21.29992442170268
weather sample 76 predicted accumated temperature 12.000262213225593
weather sample 77 predicted accumated temperature 14.600215265911984
weather sample 78 predicted accumated temperature 7.7001418718142105
weather sample 79 predicted accumated temperature 12.800147770142711
weather sample 80 predicted accumated temperature 2.5998485992496443
weather sample 81 predicted accumated temperature 24.300197871468413
weather sample 82 predicted accumated temperature 26.499484613492108
weather sample 83 predicted accumated temperature -0.5002204600932796
weather sample 84 predicted accumated temperature -1.0000080809345206
weather sample 85 predicted accumated temperature 11.499886978977216
weather sample 86 predicted accumated temperature 9.800040520716314
weather sample 87 predicted accumated temperature -7.89970943872313
weather sample 88 predicted accumated temperature 25.300190995689526
weather sample 89 predicted accumated temperature 4.9000568110323215
weather sample 90 predicted accumated temperature -12.79993140951951
weather sample 91 predicted accumated temperature 21.000163069081804
weather sample 92 predicted accumated temperature 14.600123364050749
weather sample 93 predicted accumated temperature 9.500002025073549
weather sample 94 predicted accumated temperature 18.900156671504146
weather sample 95 predicted accumated temperature 8.700187680126799
weather sample 96 predicted accumated temperature 21.30004534009889
weather sample 97 predicted accumated temperature 0.3995167255733385
weather sample 98 predicted accumated temperature 27.000189487022503
weather sample 99 predicted accumated temperature 0.19989249233445605
weather sample 100 predicted accumated temperature 8.80011530466759
weather sample 101 predicted accumated temperature 3.5001565664127225
weather sample 102 predicted accumated temperature 5.299648197857703
weather sample 103 predicted accumated temperature 11.70020735194993
weather sample 104 predicted accumated temperature 0.8999041329511588
weather sample 105 predicted accumated temperature 7.800128957652463
weather sample 106 predicted accumated temperature 7.399877326798245
weather sample 107 predicted accumated temperature -17.79980282763126
weather sample 108 predicted accumated temperature 24.200055548541425
weather sample 109 predicted accumated temperature 19.69973311559957
weather sample 110 predicted accumated temperature 4.700193320378777
weather sample 111 predicted accumated temperature 28.89995224562201
weather sample 112 predicted accumated temperature 15.999867238433938
weather sample 113 predicted accumated temperature 23.600169155395193
weather sample 114 predicted accumated temperature 22.599945965842043
weather sample 115 predicted accumated temperature 16.59971327988623
weather sample 116 predicted accumated temperature 21.600208683710317
weather sample 117 predicted accumated temperature 13.300019984152058
weather sample 118 predicted accumated temperature 22.80004135453853
weather sample 119 predicted accumated temperature 17.50022712600269
weather sample 120 predicted accumated temperature 1.7000392272598717
weather sample 121 predicted accumated temperature -18.60008772394751
weather sample 122 predicted accumated temperature 2.2001356835286057
weather sample 123 predicted accumated temperature 21.79995629394636
weather sample 124 predicted accumated temperature 22.900180915500584
weather sample 125 predicted accumated temperature 20.800209782562874
weather sample 126 predicted accumated temperature 1.0002351853975693
weather sample 127 predicted accumated temperature 17.700148208039927
weather sample 128 predicted accumated temperature 25.70025148248125
weather sample 129 predicted accumated temperature -6.300045815001262
weather sample 130 predicted accumated temperature -4.399925749879005
weather sample 131 predicted accumated temperature -0.49997463563007116
weather sample 132 predicted accumated temperature 18.800070835483925
weather sample 133 predicted accumated temperature 2.3003926582062064
weather sample 134 predicted accumated temperature 15.399070338364648
weather sample 135 predicted accumated temperature 23.79992737054797
weather sample 136 predicted accumated temperature 5.400144884343046
weather sample 137 predicted accumated temperature 0.8000621910395509
weather sample 138 predicted accumated temperature 24.900036513795122
weather sample 139 predicted accumated temperature 11.099884693019252
weather sample 140 predicted accumated temperature 16.399977995182617
weather sample 141 predicted accumated temperature 28.89990946920453
weather sample 142 predicted accumated temperature 21.29994605147215
weather sample 143 predicted accumated temperature -1.3003067408252935
weather sample 144 predicted accumated temperature 10.999839244885097
weather sample 145 predicted accumated temperature 20.70018371315828
weather sample 146 predicted accumated temperature 15.000186823515492
weather sample 147 predicted accumated temperature -0.30003457256798605
weather sample 148 predicted accumated temperature -10.90030740321359
weather sample 149 predicted accumated temperature 22.700217252864025
weather sample 150 predicted accumated temperature 18.500048550503923
weather sample 151 predicted accumated temperature 5.899579696050885
weather sample 152 predicted accumated temperature 20.200166616649444
weather sample 153 predicted accumated temperature 15.400131481634883
weather sample 154 predicted accumated temperature -1.1002859463087962
weather sample 155 predicted accumated temperature 16.000078501076658
weather sample 156 predicted accumated temperature 10.200254718449363
weather sample 157 predicted accumated temperature 6.200256816951688
weather sample 158 predicted accumated temperature -20.599767346619245
weather sample 159 predicted accumated temperature 8.800383671071597
weather sample 160 predicted accumated temperature 3.500098097159448
weather sample 161 predicted accumated temperature -3.700130066200547
weather sample 162 predicted accumated temperature 20.300058900569237
weather sample 163 predicted accumated temperature 20.60011100520658
weather sample 164 predicted accumated temperature 20.200238585378493
weather sample 165 predicted accumated temperature -1.800437527424961
weather sample 166 predicted accumated temperature 23.50018892095017
weather sample 167 predicted accumated temperature 11.499973932104787
weather sample 168 predicted accumated temperature 4.999832350480737
weather sample 169 predicted accumated temperature 26.100154995389545
weather sample 170 predicted accumated temperature -4.300464080340417
weather sample 171 predicted accumated temperature 21.700025943758153
weather sample 172 predicted accumated temperature 15.300083291573955
weather sample 173 predicted accumated temperature 15.09994558945115
weather sample 174 predicted accumated temperature 10.700060438588382
weather sample 175 predicted accumated temperature -6.799995751040051
weather sample 176 predicted accumated temperature 8.400164631834693
weather sample 177 predicted accumated temperature 24.50016371604297
weather sample 178 predicted accumated temperature -15.099776134191325
weather sample 179 predicted accumated temperature 14.599776423759174
weather sample 180 predicted accumated temperature 2.700140997441732
weather sample 181 predicted accumated temperature 1.1001532170812816
weather sample 182 predicted accumated temperature 20.000082205956964
weather sample 183 predicted accumated temperature 12.199731553364003
weather sample 184 predicted accumated temperature 18.499734668938434
weather sample 185 predicted accumated temperature -5.399910568769442
weather sample 186 predicted accumated temperature 21.800139142568064
weather sample 187 predicted accumated temperature 10.700311049415703
weather sample 188 predicted accumated temperature -1.7998863344979021
weather sample 189 predicted accumated temperature 7.300294496508932
weather sample 190 predicted accumated temperature 15.699856013483444
weather sample 191 predicted accumated temperature -3.400005933699598
weather sample 192 predicted accumated temperature -6.100666962056721
weather sample 193 predicted accumated temperature 28.799468797968686
weather sample 194 predicted accumated temperature 2.000346236510163
weather sample 195 predicted accumated temperature 3.9997288521342993
weather sample 196 predicted accumated temperature 18.299774887303954
weather sample 197 predicted accumated temperature -13.399999487704067
weather sample 198 predicted accumated temperature 11.300206523984135
weather sample 199 predicted accumated temperature 3.7000292277589137
weather sample 200 predicted accumated temperature 26.900114842583136
weather sample 201 predicted accumated temperature 14.399492689885307
weather sample 202 predicted accumated temperature -10.400193003718146
weather sample 203 predicted accumated temperature -17.100012159692078
weather sample 204 predicted accumated temperature 16.400103745625856
weather sample 205 predicted accumated temperature 24.599993913250415
weather sample 206 predicted accumated temperature -7.999996111610342
weather sample 207 predicted accumated temperature 13.200019441000727
weather sample 208 predicted accumated temperature 16.200071817258795
weather sample 209 predicted accumated temperature 15.100220123685258
weather sample 210 predicted accumated temperature -13.69970333749677
weather sample 211 predicted accumated temperature 19.50018083717151
weather sample 212 predicted accumated temperature 8.600225961291962
weather sample 213 predicted accumated temperature -0.6997687264110688
weather sample 214 predicted accumated temperature 20.10004054183488
weather sample 215 predicted accumated temperature -0.5000073389987918
weather sample 216 predicted accumated temperature -3.199797279261256
weather sample 217 predicted accumated temperature 1.3997479516504239
weather sample 218 predicted accumated temperature 30.199903630783027
weather sample 219 predicted accumated temperature 21.900203964583064
weather sample 220 predicted accumated temperature -1.8998058537081999
weather sample 221 predicted accumated temperature -16.00008429100049
weather sample 222 predicted accumated temperature 30.099926284505614
weather sample 223 predicted accumated temperature 21.700239144785456
weather sample 224 predicted accumated temperature 12.099934768329817
weather sample 225 predicted accumated temperature -1.4002939422577327
weather sample 226 predicted accumated temperature 0.3997340787402024
weather sample 227 predicted accumated temperature 16.69976423406778
weather sample 228 predicted accumated temperature 19.700046124787555
weather sample 229 predicted accumated temperature 5.299866574507379
weather sample 230 predicted accumated temperature 17.30016622128673
weather sample 231 predicted accumated temperature -3.600008615498062
weather sample 232 predicted accumated temperature -17.999794742651673
weather sample 233 predicted accumated temperature 14.20004741569253
weather sample 234 predicted accumated temperature 6.599630458958151
weather sample 235 predicted accumated temperature 21.599826569453977
weather sample 236 predicted accumated temperature 23.600212951062076
weather sample 237 predicted accumated temperature 13.899876942019235
weather sample 238 predicted accumated temperature 1.1001077798097798
weather sample 239 predicted accumated temperature 8.000231598225557
weather sample 240 predicted accumated temperature 15.399693280399362
weather sample 241 predicted accumated temperature 6.399773909244422
weather sample 242 predicted accumated temperature 23.400263237288975
weather sample 243 predicted accumated temperature -13.899685707495737
weather sample 244 predicted accumated temperature -2.3000609625344524
weather sample 245 predicted accumated temperature 20.099560298809212
weather sample 246 predicted accumated temperature 25.200183406141946
weather sample 247 predicted accumated temperature 7.000139876431054
weather sample 248 predicted accumated temperature 10.29968916002054
weather sample 249 predicted accumated temperature 5.1001743280369185
weather sample 250 predicted accumated temperature -19.500161365976908
weather sample 251 predicted accumated temperature 20.600174236076363
weather sample 252 predicted accumated temperature 23.200157752465813
weather sample 253 predicted accumated temperature 21.40005909821511
weather sample 254 predicted accumated temperature 10.499976414340601
weather sample 255 predicted accumated temperature -2.5997613178137158
weather sample 256 predicted accumated temperature 15.299649813721608
weather sample 257 predicted accumated temperature 21.99954215225267
weather sample 258 predicted accumated temperature 25.800207659837795
weather sample 259 predicted accumated temperature 9.800007628478115
weather sample 260 predicted accumated temperature 20.600227938842867
weather sample 261 predicted accumated temperature -19.99980999945072
weather sample 262 predicted accumated temperature 22.00025168359321
weather sample 263 predicted accumated temperature 28.10022537620027
weather sample 264 predicted accumated temperature 21.400154376721225
weather sample 265 predicted accumated temperature 6.599872348038513
weather sample 266 predicted accumated temperature -13.199682233860754
weather sample 267 predicted accumated temperature 23.10015439476222
weather sample 268 predicted accumated temperature -2.8997824752572043
weather sample 269 predicted accumated temperature 5.29988308183329
weather sample 270 predicted accumated temperature 12.19910009132717
weather sample 271 predicted accumated temperature -9.199735951311355
weather sample 272 predicted accumated temperature 2.6001852310188998
weather sample 273 predicted accumated temperature 27.20009857680217
weather sample 274 predicted accumated temperature 3.0996007587233754
weather sample 275 predicted accumated temperature -2.1997842128184466
weather sample 276 predicted accumated temperature 25.39993932777837
weather sample 277 predicted accumated temperature 15.899585243728161
weather sample 278 predicted accumated temperature 10.300095083749346
weather sample 279 predicted accumated temperature 14.70022496438381
weather sample 280 predicted accumated temperature -7.59982253990764
weather sample 281 predicted accumated temperature 12.800195271446313
weather sample 282 predicted accumated temperature 23.9000714552468
weather sample 283 predicted accumated temperature 8.5997337032183
weather sample 284 predicted accumated temperature 27.90011356775711
weather sample 285 predicted accumated temperature -0.000571241459155658
weather sample 286 predicted accumated temperature 20.600202195037728
weather sample 287 predicted accumated temperature 10.99989989657923
weather sample 288 predicted accumated temperature 1.700019688139549

## **Evaluate Model Performance**

In [33]:
# Calculate performance metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R² Score: {r2}")

Mean Squared Error (MSE): 7.128190685546784e-08
R² Score: 0.9999999995078022

## **Apprant temperature (Feels like temperatures)**

# **Since There is no apparent temprature column is your data set first we will compute apprant temprature column scientific formula to calculate apprant temprature**
# The apparent temperature (feels-like temperature) is calculated using meteorological models that take into account:
# New section
# Temperature
# Humidity
# Wind Speed

# The formula used by the Meteorology is:https://www.vcalc.com/wiki/australian-apparent-temperature

In [34]:

# Convert Wind Speed from km/h to m/s
data['Wind Speed_m/s']=data['Wind Speed_km/h']/3.6

# Calculate water vapor pressure (e)
data["e"] = (data["Rel Hum_%"] / 100) * (6.105 * np.exp((17.27 * data["Temp_C"]) / (data["Temp_C"] + 237.7)))


# Calculate Apparent Temperature
data["Apparent_Temp_C"] = data["Temp_C"] + (0.33 * data["e"]) - (0.70 * data["Wind Speed_m/s"]) - 4.00


# Display first few rows
print(data[["Temp_C", "Rel Hum_%", "Wind Speed_km/h", "Apparent_Temp_C"]].head())

   Temp_C  Rel Hum_%  Wind Speed_km/h  Apparent_Temp_C
0    -1.8         86                4        -5.059090
1    -1.8         87                4        -5.041431
2    -1.8         89                7        -5.589446
3    -1.5         88                6        -5.077932
4    -1.5         88                7        -5.272376

## **Selecting feature**

In [36]:
X=data[['Temp_C', 'Rel Hum_%', 'Wind Speed_km/h', 'Visibility_km', 'Press_kPa']]
y=data['Apparent_Temp_C']

## **Splititng data**

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## **Scaling Features**

In [38]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## **Ridge Regression Model**

In [39]:
ridge = Ridge()

# Hyperparameter Grid (alpha for Ridge)
param_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}

# Perform GridSearchCV to tune the hyperparameters
grid_search = GridSearchCV(estimator=ridge, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_squared_error')

## **Best Hyperparameter**

In [40]:
best_alpha = grid_search.best_params_['alpha']
best_score = grid_search.best_score_

## **Train the best model using the best alpha**

In [41]:
best_model = grid_search.best_estimator_
best_model.fit(X_train_scaled, y_train)

Ridge(alpha=0.01)

## **Predicting the Apprent Temp**

In [42]:
# Make predictions
y_pred=best_model.predict(X_test_scaled)

In [43]:
for i ,prediction in enumerate(y_pred):
  print(f"Weather sample {i+1} apprent temprature(feels like temp) :{prediction} ")

Weather sample 1 apprent temprature(feels like temp) :9.70602793543559
Weather sample 2 apprent temprature(feels like temp) :-5.387564503803282
Weather sample 3 apprent temprature(feels like temp) :8.232488662010832
Weather sample 4 apprent temprature(feels like temp) :6.778728582743797
Weather sample 5 apprent temprature(feels like temp) :-17.798039167272982
Weather sample 6 apprent temprature(feels like temp) :20.508739034581144
Weather sample 7 apprent temprature(feels like temp) :-14.354861782301445
Weather sample 8 apprent temprature(feels like temp) :15.225064559140062
Weather sample 9 apprent temprature(feels like temp) :20.599941734807143
Weather sample 10 apprent temprature(feels like temp) :-25.058986033651458
Weather sample 11 apprent temprature(feels like temp) :15.414155927620314
Weather sample 12 apprent temprature(feels like temp) :20.07069460656225
Weather sample 13 apprent temprature(feels like temp) :20.631272739886334
Weather sample 14 apprent temprature(feels like temp) :-0.44935046995420347
Weather sample 15 apprent temprature(feels like temp) :12.71958320372282
Weather sample 16 apprent temprature(feels like temp) :-6.272960220869689
Weather sample 17 apprent temprature(feels like temp) :0.5214875566229926
Weather sample 18 apprent temprature(feels like temp) :1.9629127057494937
Weather sample 19 apprent temprature(feels like temp) :14.504716444900144
Weather sample 20 apprent temprature(feels like temp) :-3.400035800826781
Weather sample 21 apprent temprature(feels like temp) :10.446042181029714
Weather sample 22 apprent temprature(feels like temp) :-4.693757939051774
Weather sample 23 apprent temprature(feels like temp) :17.00851416103036
Weather sample 24 apprent temprature(feels like temp) :11.897469246604363
Weather sample 25 apprent temprature(feels like temp) :-6.740152726795972
Weather sample 26 apprent temprature(feels like temp) :-6.72186414590895
Weather sample 27 apprent temprature(feels like temp) :0.22950757959873513
Weather sample 28 apprent temprature(feels like temp) :1.5731360098912437
Weather sample 29 apprent temprature(feels like temp) :-0.3937317917708043
Weather sample 30 apprent temprature(feels like temp) :11.524569703336251
Weather sample 31 apprent temprature(feels like temp) :21.896726955115824
Weather sample 32 apprent temprature(feels like temp) :-13.547555873857398
Weather sample 33 apprent temprature(feels like temp) :-6.649136575553004
Weather sample 34 apprent temprature(feels like temp) :22.20647658433779
Weather sample 35 apprent temprature(feels like temp) :10.279901810587145
Weather sample 36 apprent temprature(feels like temp) :21.8086614915724
Weather sample 37 apprent temprature(feels like temp) :4.9643814375008715
Weather sample 38 apprent temprature(feels like temp) :9.265159636777511
Weather sample 39 apprent temprature(feels like temp) :22.110759549397816
Weather sample 40 apprent temprature(feels like temp) :4.057504093893026
Weather sample 41 apprent temprature(feels like temp) :-16.554009897784024
Weather sample 42 apprent temprature(feels like temp) :-11.485411138279655
Weather sample 43 apprent temprature(feels like temp) :-13.339196145028545
Weather sample 44 apprent temprature(feels like temp) :-8.145256066240975
Weather sample 45 apprent temprature(feels like temp) :11.953520645419015
Weather sample 46 apprent temprature(feels like temp) :27.36502341884353
Weather sample 47 apprent temprature(feels like temp) :-18.57808415025642
Weather sample 48 apprent temprature(feels like temp) :3.6103898782285597
Weather sample 49 apprent temprature(feels like temp) :12.682049572734456
Weather sample 50 apprent temprature(feels like temp) :8.378788126385365
Weather sample 51 apprent temprature(feels like temp) :22.27275204769961
Weather sample 52 apprent temprature(feels like temp) :-4.6741609126118915
Weather sample 53 apprent temprature(feels like temp) :-0.38491284873334575
Weather sample 54 apprent temprature(feels like temp) :5.672438320347464
Weather sample 55 apprent temprature(feels like temp) :26.97823389403698
Weather sample 56 apprent temprature(feels like temp) :-6.253116750339843
Weather sample 57 apprent temprature(feels like temp) :22.873207736959667
Weather sample 58 apprent temprature(feels like temp) :11.82410504352282
Weather sample 59 apprent temprature(feels like temp) :-19.760907467421152
Weather sample 60 apprent temprature(feels like temp) :16.895362380480165
Weather sample 61 apprent temprature(feels like temp) :-16.40502354059076
Weather sample 62 apprent temprature(feels like temp) :25.275372726250232
Weather sample 63 apprent temprature(feels like temp) :0.13918872530978454
Weather sample 64 apprent temprature(feels like temp) :-7.726274149604996
Weather sample 65 apprent temprature(feels like temp) :-4.548854851372323
Weather sample 66 apprent temprature(feels like temp) :19.157984246257293
Weather sample 67 apprent temprature(feels like temp) :26.38905075263425
Weather sample 68 apprent temprature(feels like temp) :25.05674835604302
Weather sample 69 apprent temprature(feels like temp) :-4.376021956983945
Weather sample 70 apprent temprature(feels like temp) :14.527238958503755
Weather sample 71 apprent temprature(feels like temp) :8.505354050126535
Weather sample 72 apprent temprature(feels like temp) :-18.68673129879615
Weather sample 73 apprent temprature(feels like temp) :-2.9663113693356413
Weather sample 74 apprent temprature(feels like temp) :-10.74114618031027
Weather sample 75 apprent temprature(feels like temp) :21.43702637386402
Weather sample 76 apprent temprature(feels like temp) :5.567356910425138
Weather sample 77 apprent temprature(feels like temp) :12.702041407281747
Weather sample 78 apprent temprature(feels like temp) :0.23277962718365952
Weather sample 79 apprent temprature(feels like temp) :11.414538930887634
Weather sample 80 apprent temprature(feels like temp) :-4.409326103174071
Weather sample 81 apprent temprature(feels like temp) :23.713273845977195
Weather sample 82 apprent temprature(feels like temp) :24.71907377873255
Weather sample 83 apprent temprature(feels like temp) :-4.425609752953329
Weather sample 84 apprent temprature(feels like temp) :-4.7806322845709035
Weather sample 85 apprent temprature(feels like temp) :10.217920637641345
Weather sample 86 apprent temprature(feels like temp) :5.9752321711116805
Weather sample 87 apprent temprature(feels like temp) :-17.742181545335693
Weather sample 88 apprent temprature(feels like temp) :23.241008941806694
Weather sample 89 apprent temprature(feels like temp) :-0.471397944862475
Weather sample 90 apprent temprature(feels like temp) :-18.22346892813028
Weather sample 91 apprent temprature(feels like temp) :18.8605434299823
Weather sample 92 apprent temprature(feels like temp) :12.16598822475125
Weather sample 93 apprent temprature(feels like temp) :9.037565532304647
Weather sample 94 apprent temprature(feels like temp) :18.087944583585003
Weather sample 95 apprent temprature(feels like temp) :5.246587318380577
Weather sample 96 apprent temprature(feels like temp) :21.630805215514826
Weather sample 97 apprent temprature(feels like temp) :-3.287701240747807
Weather sample 98 apprent temprature(feels like temp) :25.896226598740505
Weather sample 99 apprent temprature(feels like temp) :-5.427647998660105
Weather sample 100 apprent temprature(feels like temp) :5.992524901985166
Weather sample 101 apprent temprature(feels like temp) :-4.388113290742754
Weather sample 102 apprent temprature(feels like temp) :-1.7785047885166234
Weather sample 103 apprent temprature(feels like temp) :4.09333805897817
Weather sample 104 apprent temprature(feels like temp) :-5.811595365108244
Weather sample 105 apprent temprature(feels like temp) :0.7832275703916407
Weather sample 106 apprent temprature(feels like temp) :1.5458559412229338
Weather sample 107 apprent temprature(feels like temp) :-26.88753396844891
Weather sample 108 apprent temprature(feels like temp) :22.667834634954513
Weather sample 109 apprent temprature(feels like temp) :19.359709330602588
Weather sample 110 apprent temprature(feels like temp) :-1.8728526728520638
Weather sample 111 apprent temprature(feels like temp) :27.994119351986097
Weather sample 112 apprent temprature(feels like temp) :14.741282194996597
Weather sample 113 apprent temprature(feels like temp) :21.489963004848036
Weather sample 114 apprent temprature(feels like temp) :21.8322125652946
Weather sample 115 apprent temprature(feels like temp) :15.040212956068913
Weather sample 116 apprent temprature(feels like temp) :21.82191915356824
Weather sample 117 apprent temprature(feels like temp) :13.594629704988225
Weather sample 118 apprent temprature(feels like temp) :22.756255894065756
Weather sample 119 apprent temprature(feels like temp) :16.479539224953683
Weather sample 120 apprent temprature(feels like temp) :-4.640048480088365
Weather sample 121 apprent temprature(feels like temp) :-25.10271380388834
Weather sample 122 apprent temprature(feels like temp) :-5.557094535920343
Weather sample 123 apprent temprature(feels like temp) :22.017097576840683
Weather sample 124 apprent temprature(feels like temp) :21.588963749261
Weather sample 125 apprent temprature(feels like temp) :21.892055993361225
Weather sample 126 apprent temprature(feels like temp) :-7.232452576505094
Weather sample 127 apprent temprature(feels like temp) :16.38239303486978
Weather sample 128 apprent temprature(feels like temp) :24.460413851947962
Weather sample 129 apprent temprature(feels like temp) :-10.93058735384066
Weather sample 130 apprent temprature(feels like temp) :-11.53471893206332
Weather sample 131 apprent temprature(feels like temp) :-3.9860933858565764
Weather sample 132 apprent temprature(feels like temp) :18.648268966613234
Weather sample 133 apprent temprature(feels like temp) :-4.791660660461111
Weather sample 134 apprent temprature(feels like temp) :9.286438511047544
Weather sample 135 apprent temprature(feels like temp) :22.141290022740062
Weather sample 136 apprent temprature(feels like temp) :-1.90259491082373
Weather sample 137 apprent temprature(feels like temp) :-4.627045524038103
Weather sample 138 apprent temprature(feels like temp) :24.77922612811953
Weather sample 139 apprent temprature(feels like temp) :9.509485664382577
Weather sample 140 apprent temprature(feels like temp) :12.898520528596775
Weather sample 141 apprent temprature(feels like temp) :26.337618727039832
Weather sample 142 apprent temprature(feels like temp) :20.181203906260052
Weather sample 143 apprent temprature(feels like temp) :-4.881365684683906
Weather sample 144 apprent temprature(feels like temp) :8.558422983245865
Weather sample 145 apprent temprature(feels like temp) :18.88812915831145
Weather sample 146 apprent temprature(feels like temp) :11.794700328228378
Weather sample 147 apprent temprature(feels like temp) :-6.943873908716557
Weather sample 148 apprent temprature(feels like temp) :-15.233961130163607
Weather sample 149 apprent temprature(feels like temp) :19.390080440207598
Weather sample 150 apprent temprature(feels like temp) :16.71344800974048
Weather sample 151 apprent temprature(feels like temp) :3.3512203926478805
Weather sample 152 apprent temprature(feels like temp) :19.187932464406025
Weather sample 153 apprent temprature(feels like temp) :13.220109627973713
Weather sample 154 apprent temprature(feels like temp) :-4.6895065340567035
Weather sample 155 apprent temprature(feels like temp) :14.804031411488488
Weather sample 156 apprent temprature(feels like temp) :3.8328425376425335
Weather sample 157 apprent temprature(feels like temp) :3.8109414387142015
Weather sample 158 apprent temprature(feels like temp) :-28.54708157138805
Weather sample 159 apprent temprature(feels like temp) :4.320497293281378
Weather sample 160 apprent temprature(feels like temp) :-3.002927632005842
Weather sample 161 apprent temprature(feels like temp) :-10.448430874348375
Weather sample 162 apprent temprature(feels like temp) :17.94019855623457
Weather sample 163 apprent temprature(feels like temp) :20.123959277441795
Weather sample 164 apprent temprature(feels like temp) :19.070377744505684
Weather sample 165 apprent temprature(feels like temp) :-4.914502081113997
Weather sample 166 apprent temprature(feels like temp) :22.479607414740734
Weather sample 167 apprent temprature(feels like temp) :9.711983419708869
Weather sample 168 apprent temprature(feels like temp) :-0.2686855347159778
Weather sample 169 apprent temprature(feels like temp) :24.28915385232319
Weather sample 170 apprent temprature(feels like temp) :-7.2646165135828324
Weather sample 171 apprent temprature(feels like temp) :19.644403941522754
Weather sample 172 apprent temprature(feels like temp) :13.157123148068983
Weather sample 173 apprent temprature(feels like temp) :12.81548398559303
Weather sample 174 apprent temprature(feels like temp) :6.860181223326116
Weather sample 175 apprent temprature(feels like temp) :-14.749209149507507
Weather sample 176 apprent temprature(feels like temp) :3.0999417788085895
Weather sample 177 apprent temprature(feels like temp) :24.595752029898403
Weather sample 178 apprent temprature(feels like temp) :-25.220184575296486
Weather sample 179 apprent temprature(feels like temp) :13.772759645103712
Weather sample 180 apprent temprature(feels like temp) :-3.8313133631275766
Weather sample 181 apprent temprature(feels like temp) :-3.1036857362578862
Weather sample 182 apprent temprature(feels like temp) :16.806988689461484
Weather sample 183 apprent temprature(feels like temp) :11.842294571935518
Weather sample 184 apprent temprature(feels like temp) :18.04219369246091
Weather sample 185 apprent temprature(feels like temp) :-8.487863798772828
Weather sample 186 apprent temprature(feels like temp) :20.955875812003203
Weather sample 187 apprent temprature(feels like temp) :7.613719581888761
Weather sample 188 apprent temprature(feels like temp) :-9.46743966575906
Weather sample 189 apprent temprature(feels like temp) :4.801043643883507
Weather sample 190 apprent temprature(feels like temp) :14.90990047255126
Weather sample 191 apprent temprature(feels like temp) :-11.361682090683363
Weather sample 192 apprent temprature(feels like temp) :-10.557270431776125
Weather sample 193 apprent temprature(feels like temp) :24.51137001101143
Weather sample 194 apprent temprature(feels like temp) :-1.4359843471238856
Weather sample 195 apprent temprature(feels like temp) :0.2575422178903848
Weather sample 196 apprent temprature(feels like temp) :12.263163908301104
Weather sample 197 apprent temprature(feels like temp) :-19.51431506373492
Weather sample 198 apprent temprature(feels like temp) :5.898057781754537
Weather sample 199 apprent temprature(feels like temp) :-3.5777110877732268
Weather sample 200 apprent temprature(feels like temp) :25.230235306512174
Weather sample 201 apprent temprature(feels like temp) :11.280988614495591
Weather sample 202 apprent temprature(feels like temp) :-17.819462512853573
Weather sample 203 apprent temprature(feels like temp) :-25.24067428654359
Weather sample 204 apprent temprature(feels like temp) :9.835742378094661
Weather sample 205 apprent temprature(feels like temp) :23.09636549879606
Weather sample 206 apprent temprature(feels like temp) :-15.26938224863531
Weather sample 207 apprent temprature(feels like temp) :11.691606603311834
Weather sample 208 apprent temprature(feels like temp) :14.39206156708558
Weather sample 209 apprent temprature(feels like temp) :9.76038887731934
Weather sample 210 apprent temprature(feels like temp) :-19.586187752382422
Weather sample 211 apprent temprature(feels like temp) :17.235099338566737
Weather sample 212 apprent temprature(feels like temp) :2.4843644011712227
Weather sample 213 apprent temprature(feels like temp) :-4.127645832239588
Weather sample 214 apprent temprature(feels like temp) :18.559575163257474
Weather sample 215 apprent temprature(feels like temp) :-5.090737783855999
Weather sample 216 apprent temprature(feels like temp) :-9.388086355167303
Weather sample 217 apprent temprature(feels like temp) :-3.0034606194783384
Weather sample 218 apprent temprature(feels like temp) :29.82360573537897
Weather sample 219 apprent temprature(feels like temp) :20.657911750602878
Weather sample 220 apprent temprature(feels like temp) :-9.556443619154134
Weather sample 221 apprent temprature(feels like temp) :-21.345314656645435
Weather sample 222 apprent temprature(feels like temp) :28.701050359779266
Weather sample 223 apprent temprature(feels like temp) :21.031646701892768
Weather sample 224 apprent temprature(feels like temp) :10.882639397653953
Weather sample 225 apprent temprature(feels like temp) :-4.454282846344468
Weather sample 226 apprent temprature(feels like temp) :-5.747877815570539
Weather sample 227 apprent temprature(feels like temp) :16.822720937124092
Weather sample 228 apprent temprature(feels like temp) :18.060047193334068
Weather sample 229 apprent temprature(feels like temp) :-4.462307410233339
Weather sample 230 apprent temprature(feels like temp) :15.997204691962537
Weather sample 231 apprent temprature(feels like temp) :-8.21448805320139
Weather sample 232 apprent temprature(feels like temp) :-27.404689925392056
Weather sample 233 apprent temprature(feels like temp) :12.342192853241393
Weather sample 234 apprent temprature(feels like temp) :4.83948307652958
Weather sample 235 apprent temprature(feels like temp) :17.41537293275558
Weather sample 236 apprent temprature(feels like temp) :21.453418996718764
Weather sample 237 apprent temprature(feels like temp) :11.503911552994943
Weather sample 238 apprent temprature(feels like temp) :-8.880598511876787
Weather sample 239 apprent temprature(feels like temp) :2.793112969326384
Weather sample 240 apprent temprature(feels like temp) :9.238627416146755
Weather sample 241 apprent temprature(feels like temp) :5.844364736450709
Weather sample 242 apprent temprature(feels like temp) :23.657562893522666
Weather sample 243 apprent temprature(feels like temp) :-21.02537092240291
Weather sample 244 apprent temprature(feels like temp) :-6.325023316979055
Weather sample 245 apprent temprature(feels like temp) :16.116075180677402
Weather sample 246 apprent temprature(feels like temp) :23.735815099595307
Weather sample 247 apprent temprature(feels like temp) :1.914941042392893
Weather sample 248 apprent temprature(feels like temp) :6.836770622974042
Weather sample 249 apprent temprature(feels like temp) :0.9079123023713453
Weather sample 250 apprent temprature(feels like temp) :-26.086988441935855
Weather sample 251 apprent temprature(feels like temp) :19.996774060517094
Weather sample 252 apprent temprature(feels like temp) :23.394288479018265
Weather sample 253 apprent temprature(feels like temp) :20.833651913705086
Weather sample 254 apprent temprature(feels like temp) :6.319061595821976
Weather sample 255 apprent temprature(feels like temp) :-8.919505835003196
Weather sample 256 apprent temprature(feels like temp) :9.418064986016887
Weather sample 257 apprent temprature(feels like temp) :18.10685198454507
Weather sample 258 apprent temprature(feels like temp) :25.21868349462331
Weather sample 259 apprent temprature(feels like temp) :8.020879750842807
Weather sample 260 apprent temprature(feels like temp) :20.387239184813026
Weather sample 261 apprent temprature(feels like temp) :-28.21366883393633
Weather sample 262 apprent temprature(feels like temp) :23.201030491769558
Weather sample 263 apprent temprature(feels like temp) :27.691673426151308
Weather sample 264 apprent temprature(feels like temp) :22.042083428107322
Weather sample 265 apprent temprature(feels like temp) :4.694665934111082
Weather sample 266 apprent temprature(feels like temp) :-23.912358345958413
Weather sample 267 apprent temprature(feels like temp) :22.068914981000407
Weather sample 268 apprent temprature(feels like temp) :-8.413602580340928

## **Evaluating the model**

In [44]:

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"R² Score: {r2}")

MAE: 0.5478452089663562
MSE: 0.48429794391075914
R² Score: 0.9975812393380608